generator/src/main/java/com/scottlogic/deg/generator/decisiontree/rule_strategy/Combination.java, generator/src/main/java/com/scottlogic/deg/generator/generation/combination/Combination.java, generator/src/main/java/com/scottlogic/deg/generator/generation/combination/CombinationProducer.java, generator/src/main/java/com/scottlogic/deg/generator/generation/combination/CombinationStrategy.java, generator/src/main/java/com/scottlogic/deg/generator/generation/combination/DecisionTreeCombinationProducer.java, generator/src/main/java/com/scottlogic/deg/generator/generation/combination/SingleCombinationStrategy.java, generator/src/main/java/com/scottlogic/deg/generator/walker/ReductiveDecisionTreeWalker.java
Produce must have combinations of values in a row based on options in a
decision tree
=> Add code for value combination production

generator/src/test/java/com/scottlogic/deg/generator/cucumber/ShorterThan.feature, generator/src/test/java/com/scottlogic/deg/generator/cucumber/steps/NullValueStep.java
=> Support null value in constraint definition

docs/KeyDecisions.md, generator/docs/StringGeneration.md
Update documentation regarding #200
=> Added documentation for character support

generator/src/test/java/com/scottlogic/deg/generator/cucumber/EqualTo.feature, generator/src/test/java/com/scottlogic/deg/generator/cucumber/GranularTo.feature, generator/src/test/java/com/scottlogic/deg/generator/cucumber/GreaterThan.feature, generator/src/test/java/com/scottlogic/deg/generator/cucumber/GreaterThanOrEqualTo.feature, generator/src/test/java/com/scottlogic/deg/generator/cucumber/LessThan.feature, generator/src/test/java/com/scottlogic/deg/generator/cucumber/LessThanOrEqualTo.feature, generator/src/test/java/com/scottlogic/deg/generator/cucumber/interesting/BeforeInteresting.feature, generator/src/test/java/com/scottlogic/deg/generator/cucumber/interesting/BeforeOrAtInteresting.feature, generator/src/test/java/com/scottlogic/deg/generator/cucumber/interesting/GreaterThanInteresting.feature, generator/src/test/java/com/scottlogic/deg/generator/cucumber/steps/DateObject.java, generator/src/test/java/com/scottlogic/deg/generator/cucumber/steps/DateValueStep.java, generator/src/test/java/com/scottlogic/deg/generator/cucumber/steps/GeneralTestStep.java, generator/src/test/java/com/scottlogic/deg/generator/cucumber/steps/SetValueStep.java, generator/src/test/java/com/scottlogic/deg/generator/cucumber/steps/TypeRegistryConfiguration.java, generator/src/test/java/com/scottlogic/deg/generator/cucumber/utils/DegTestState.java, generator/src/test/java/com/scottlogic/deg/generator/cucumber/utils/GeneratorTestUtilities.java
Primary goal: Ensure values are passed into the cucumber framework consistently.
Also resolves #259
=> Cucumber value injection consistency

generator/docs/GeneratorSetup.md
Documentation, added maven
Documentation, added maven
relates to #447
=> docs: added maven to instructions

docs/Schema.md, generator/src/main/java/com/scottlogic/deg/generator/inputs/ProfileReader.java, generator/src/main/java/com/scottlogic/deg/generator/outputs/TestCaseGenerationResultWriter.java, generator/src/main/java/com/scottlogic/deg/generator/outputs/dataset_writers/CsvDataSetWriter.java, generator/src/main/java/com/scottlogic/deg/generator/outputs/dataset_writers/DataSetWriter.java, generator/src/main/java/com/scottlogic/deg/generator/outputs/dataset_writers/JsonDataSetWriter.java, generator/src/main/java/com/scottlogic/deg/generator/outputs/dataset_writers/MultiDataSetWriter.java, generator/src/main/java/com/scottlogic/deg/generator/outputs/dataset_writers/SourceTracingDataSetWriter.java, generator/src/main/java/com/scottlogic/deg/generator/outputs/targets/DirectoryOutputTarget.java, generator/src/main/java/com/scottlogic/deg/generator/outputs/targets/FileOutputTarget.java, generator/src/test/java/com/scottlogic/deg/generator/smoke_tests/ExampleProfilesTests.java
Resolve some simple bugs found when testing the utility
1. If a relative path is specified for the output file, treat the file as within the working directory - Resolves #461 
1. More descriptive error is reported when an invalid profile is provided - Resolves #463 
1. Updated [documentation](https://github.com/ScottLogic/data-engineering-generator/blob/master/docs/Schema.md#sample-file) to be valid - Resolves #468 
1. Updated to use given filename for output, but also more correctly create filenames for violations - Resolves #460
=> Various fixes to generator usage

docs/Options/GenerateOptions.md, docs/PresentationalConstraints.md, generator/docs/TreeWalkerTypes.md
Spotted some broken links in the documentation so updated to fix
=> fixed broken links

.github/ISSUE_TEMPLATE/Feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Updates to issue and pull-request templates to clearly call out things to include and consider
- Update to feature-request template to prompt for the inclusion of acceptance criteria
- Update pull-request template to clarify expected content and things to consider for every change
Resolves #476
=> Update issue and pull-request templates

README.md, generator/pom.xml, pom.xml, schemas/pom.xml
updated pom files to allow the creation of an executable jar with all dependencies
root `README.md` updated with new instructions to create the documentation site and executable jar file.
root `pom.xml` file has reporting setup so that project documentation can be generated.
generator `pom.xml` has been updated with new <build> level plugin `maven-surefire-plugin` which created the jar file including dependencies.
root level readme.md file updated with new instructions
Resolves #499
=> added assembly step to create executable jar file

generator/src/main/java/com/scottlogic/deg/generator/walker/reductive/ReductiveIterationVisualiser.java
Fixes to allow use of the ReductiveIterationVisualiser
- Updated `ReductiveIterationVisualiser` to instruct Google Guice how to satisfy its dependencies
- Manually tested
- Resolves #543
=> Fix for reductive iteration visualiser for IoC

generator/src/main/java/com/scottlogic/deg/generator/inputs/profileviolation/IndividualRuleProfileViolator.java, generator/src/test/java/com/scottlogic/deg/generator/builders/AndBuilder.java, generator/src/test/java/com/scottlogic/deg/generator/builders/BaseConstraintBuilder.java, generator/src/test/java/com/scottlogic/deg/generator/builders/ConstraintChainBuilder.java, generator/src/test/java/com/scottlogic/deg/generator/builders/ElseBuilder.java, generator/src/test/java/com/scottlogic/deg/generator/builders/IfBuilder.java, generator/src/test/java/com/scottlogic/deg/generator/builders/OrBuilder.java, generator/src/test/java/com/scottlogic/deg/generator/builders/RuleBuilder.java, generator/src/test/java/com/scottlogic/deg/generator/builders/SingleConstraintBuilder.java, generator/src/test/java/com/scottlogic/deg/generator/builders/ThenBuilder.java, generator/src/test/java/com/scottlogic/deg/generator/inputs/profileviolation/ProfileViolationTests.java, generator/src/test/java/com/scottlogic/deg/generator/inputs/profileviolation/TypeEqualityHelper.java
Starting work for profile violation tests including some new constraint builder methods and an IfBuilder. The tests added check that nested if statements violate correctly.
* Added IfBuilder and subsequent required classes
* Introduced copy method for builders to make builders immutable
* Added nested if tests to profile violation tests
* Partially resolves some parts of #648 
Related to #603
=> 603 high risk profile violation

generator/src/test/java/com/scottlogic/deg/generator/cucumber/MatchingRegex.feature
- Removal of duplicate tests from other feature files
- Addition of not tests as identified in the test matrix
- Some formatting standardisation
#411
=> Restructure CI tests for matchingRegex:

generator/src/test/java/com/scottlogic/deg/generator/cucumber/AValid.feature
- Removal of duplicate tests from other feature files
- Addition of not tests as identified in the test matrix
- Some formatting standardisation
Resolves #687
=> #687 Restructure CI tests for aValid:

generator/src/test/java/com/scottlogic/deg/generator/cucumber/LessThanOrEqualTo.feature
Restructure CI tests for LessThanOrEqualTo:
- Removal of duplicate tests from other feature files
- Addition of not tests as identified in the test matrix
- Some formatting standardisation
Resolves #313
=> #313 Restructure CI tests for LessThanOrEqualTo:

generator/src/test/java/com/scottlogic/deg/generator/cucumber/GreaterThanOrEqualTo.feature
- Removal of duplicate tests from other feature files
- Addition of not tests as identified in the test matrix
- Some formatting standardisation
Resolves #315
=> #315 Restructure CI tests for greaterThanOrEqualTo:

.circleci/config.yml, README.md
Updating GitHub to build and run tests through a different platform to:
Resolves #702
=> Circleci integration

generator/src/test/java/com/scottlogic/deg/generator/cucumber/Before.feature
Scenario that was ignored and bug raised for now passes
- Reintroduce scenario
Resolves #613
=> 613- Reintroduced ignored scenario that now passes

generator/src/test/java/com/scottlogic/deg/generator/cucumber/After.feature
Ignores test based on defect #191
=> Set test in After.feature to ignore based on defect #191

generator/src/test/java/com/scottlogic/deg/generator/cucumber/utils/Contradictions.feature
Should catch regression on #747
=> 747 - Added cucumber tests for contradictions in profiles.

generator/src/test/java/com/scottlogic/deg/generator/cucumber/AfterOrAt.feature
Updated existing tests and added new tests for afterOrAt according to the test matrix 
All tests has been added and retested ignored tests related to #611  as well. 
Resolves #310
=> 310 - Updated and added tests for afterOrAt according to matrix

README.md
Instead of `--overwrite`
Readme includes incorrect detail of the --replace switch
- Update `--overwrite` with `--replace`
=> Update README.md with --replace switch

generator/src/main/java/com/scottlogic/deg/generator/commandline/GenerateCommandLine.java
Urgent fix for CLI switch default value
Resolves #768
=> 768- Remove erroneous default from commandline

.circleci/config.yml
Removes codecov reporting.
Contrary to PR #762
=> Remove codecov reports

generator/docs/StringGeneration.md
Increased documentation for how the Automaton works when generating strings
Related to #849
=> 849 string docs update

generator/src/test/java/com/scottlogic/deg/generator/cucumber/features/operators/GranularTo.feature
Added a test for granular to 1 and granular to 0.1. 
...Added test for granular to 1 and granular to 0.1
...Removed few ignored tests 
#312
=> 312 - Granular to tests

generator/src/test/java/com/scottlogic/deg/generator/cucumber/features/operators/temporal/After.feature
Un-ignored one test which now passes in After.feature
Resolves #191
=> 191 - Recheck temporal bug

generator/src/test/java/com/scottlogic/deg/generator/cucumber/features/operators/grammatical/If.feature
Rechecked tests currently ignored due to #363. 
Unignored and fixed some tests in If.feature to use granularTo correctly. One still failing.
#363
=> 363 recheck granular to bug

generator/src/main/java/com/scottlogic/deg/generator/generation/AutomatonUtils.java, generator/src/main/java/com/scottlogic/deg/generator/generation/RegexStringGenerator.java
Rename class to match expectation
- Rename only
Related to #849
=> 849- Rename AutomationUtils -> AutomatonUtils

README.md
Replace the outdated CLI syntax
`--overwrite` 
with 
`--replace`
=> Update README to use correct/updated syntax

.github/ISSUE_TEMPLATE/Feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Updated issue and pull request templates
- Include user story prompt in feature request template
- Simplification of pull request template
=> Update GitHub templates

README.md
Fixed a typo. 
Removed use of `--dont-violate=null` as it isn't supported.
Resolves #900
=> 900 - Rework/Fix Getting Started Guide

.circleci/config.yml, .codecov.yml
It doesn't provide access to the test reports as I previously believed.
Reports are confusing and adding noise
- Disable commenting, continue collecting coverage details
=> Disable codecov

docs/GeneratorDeveloperGuide.md
=> Fix link in Developer Guide

generator/src/test/java/com/scottlogic/deg/generator/cucumber/features/Contradictions.feature, generator/src/test/java/com/scottlogic/deg/generator/cucumber/features/operators/EqualTo.feature, generator/src/test/java/com/scottlogic/deg/generator/cucumber/features/operators/GranularTo-Decimal.feature, generator/src/test/java/com/scottlogic/deg/generator/cucumber/features/operators/InSet.feature, generator/src/test/java/com/scottlogic/deg/generator/cucumber/features/operators/string/LongerThan.feature, generator/src/test/java/com/scottlogic/deg/generator/cucumber/features/operators/temporal/AfterOrAt.feature, generator/src/test/java/com/scottlogic/deg/generator/cucumber/features/operators/temporal/Before.feature, generator/src/test/java/com/scottlogic/deg/generator/cucumber/features/types/Integer.feature
Went through the existing cucumber suite. Some ignored tests were un-skipped as:
- Either the test is passing now after some bug was fixed.
- Or the test was not correctly written.
=> fixing and unskipping some tests

generator/src/main/java/com/scottlogic/deg/generator/constraints/atomic/AtomicConstraint.java, generator/src/main/java/com/scottlogic/deg/generator/decisiontree/NodeVisitor.java, generator/src/main/java/com/scottlogic/deg/generator/decisiontree/TreeConstraintNode.java, generator/src/main/java/com/scottlogic/deg/generator/decisiontree/visualisation/BaseVisitor.java, generator/src/main/java/com/scottlogic/deg/generator/walker/reductive/fieldselectionstrategy/AtomicConstraintCollector.java
removed visiting of atomic constraints from node visiting responsibility
Blocking generator modularisation
Related to #909
=> 909 - Remove atomic constraints from node visitor

docs/GettingStarted/CreatingAProfile.md, docs/Options/GenerateOptions.md, docs/Schema.md
=> fixing some links in the documentation

generator/src/main/java/com/scottlogic/deg/generator/commandline/GenerateCommandLine.java, generator/src/main/java/com/scottlogic/deg/generator/generation/DecisionTreeDataGenerator.java, generator/src/main/java/com/scottlogic/deg/generator/generation/GenerationConfig.java, generator/src/main/java/com/scottlogic/deg/generator/generation/GenerationConfigSource.java, generator/src/test/java/com/scottlogic/deg/generator/cucumber/testframework/steps/GeneralTestStep.java, generator/src/test/java/com/scottlogic/deg/generator/cucumber/testframework/utils/CucumberGenerationConfigSource.java, generator/src/test/java/com/scottlogic/deg/generator/cucumber/testframework/utils/CucumberTestState.java, generator/src/test/java/com/scottlogic/deg/generator/generation/TestGenerationConfigSource.java
simplify config constraints and how they are used in picocli
Related to #909
=> 909 Simplify config constants

.circleci/config.yml, common/src/test/java/com/scottlogic/deg/common/profile/ProfileFieldsTests.java
Enable circlecli tests in common
Related to #909
=> 909 Enable circleci tests in common module

generator/src/main/java/com/scottlogic/deg/generator/commandline/OutputTargetSpecificationImpl.java, generator/src/main/java/com/scottlogic/deg/generator/guice/BaseModule.java, generator/src/main/java/com/scottlogic/deg/generator/outputs/manifest/JsonManifestWriter.java, generator/src/main/java/com/scottlogic/deg/generator/utils/FileUtils.java, generator/src/main/java/com/scottlogic/deg/generator/utils/FileUtilsImpl.java, generator/src/main/java/com/scottlogic/deg/generator/violations/ViolationGenerationEngine.java
This PR takes the FileUtils changes alone from PR #968, as they can be isolated and are not wedded closely to that piece
The `FileUtils` class has been moved to `FileUtilsImpl`, and a `FileUtils` interface created.
=> FileUtils refactoring

docs/GeneratorDeveloperGuide.md, docs/GettingStarted/GeneratingData.md, docs/ProfileDeveloperGuide.md, generator/docs/GeneratorSetup.md
=> Docs update for "Build and Run" instructions.

orchestrator/build.gradle
Fix runtime issue with `java -j generator.jar` command
Manifest specified in `build.gradle` updated.
Resolves #991
=> #991 Fix issue in orchestrator project fatJar manifest

README.md, docs/GettingStarted/GeneratingData.md, docs/Options/ViolateOptions.md, generator/README.md, generator/docs/DeliberateViolation.md, generator/docs/GeneratorSetup.md
- Updated documentation that referred to `generate --violate` 
- Added a new document to describe command-line options for the `violate` command.
Resolves #994
=> #994 Update documentation on violation

common/src/main/java/com/scottlogic/deg/common/profile/constraints/atomic/StandardConstraintTypes.java, generator/src/main/java/com/scottlogic/deg/generator/fieldspecs/FieldSpecFactory.java, generator/src/main/java/com/scottlogic/deg/generator/generation/RicStringGenerator.java, generator/src/main/java/com/scottlogic/deg/generator/restrictions/MatchesStandardStringRestrictions.java, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/string/AValid.feature, profile/src/main/java/com/scottlogic/deg/profile/reader/BaseAtomicConstraintReaderLookup.java
create RicStringGenerator which is a RegexStringGenerator with RIC regex
Resolves #940
=> 940 RicStringGenerator

generator/src/main/java/com/scottlogic/deg/generator/guice/MonitorProvider.java, generator/src/main/java/com/scottlogic/deg/generator/walker/reductive/ReductiveIterationVisualiser.java, orchestrator/src/main/java/com/scottlogic/deg/orchestrator/generate/GenerateCommandLine.java, orchestrator/src/main/java/com/scottlogic/deg/orchestrator/violate/ViolateOutputValidator.java, orchestrator/src/main/java/com/scottlogic/deg/orchestrator/visualise/VisualiseExecute.java, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/utils/CucumberGenerationConfigSource.java, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/violate/ViolateOutputValidatorTests.java, output/src/main/java/com/scottlogic/deg/output/OutputPath.java, output/src/main/java/com/scottlogic/deg/output/guice/OutputConfigSource.java, output/src/main/java/com/scottlogic/deg/output/guice/OutputModule.java, output/src/main/java/com/scottlogic/deg/output/guice/SingleDatasetOutputTargetProvider.java, output/src/main/java/com/scottlogic/deg/output/manifest/JsonManifestWriter.java, output/src/main/java/com/scottlogic/deg/output/outputtarget/FileOutputTarget.java, output/src/main/java/com/scottlogic/deg/output/outputtarget/OutputTargetFactory.java, output/src/main/java/com/scottlogic/deg/output/outputtarget/StdoutOutputTarget.java, output/src/test/java/com/scottlogic/deg/output/writer/FileOutputTargetTests.java
Create StdoutOutputTarget
Allow path parameter to be optional, if not chosen, use Stdout
Resolves #440 
Resolves #974
=> 440 stdout

generator/src/main/java/com/scottlogic/deg/generator/generation/FieldSpecValueGenerator.java, orchestrator/build.gradle
=> re enable full-sequential. set random to default

.github/CONTRIBUTING.md
Allow auto-generated equals methods to not require additional formatting, as previously defined in the coding guidelines.
=> Minor update to code guidelines

README.md, generator/docs/DockerSetup.md, generator/docs/GeneratorSetup.md
Document the ability to build a docker image
Based on @sroebuck 's PR description in https://github.com/ScottLogic/datahelix/pull/1033 with some changes to make it more platform-independent.
=> Update documentation to discuss Docker

docs/ProfileDeveloperGuide.md
- Fix some grammatical errors
- Update some dead links
- Remove out of date information
=> Update Profile Developer Guide

orchestrator/src/test/java/com/scottlogic/deg/orchestrator/endtoend/JarExecuteTests.java, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/endtoend/loadfiletest.profile.json, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/endtoend/testfile.csv
This test runs the generator from the jar and checks that it successfully loads a csv file and generates using it.
=> Add e2e test for loading from file

docs/ProfileDeveloperGuide.md, examples/from-file/profile.json, generator/src/main/java/com/scottlogic/deg/generator/generation/GenerationConfigSource.java, orchestrator/src/main/java/com/scottlogic/deg/orchestrator/App.java, orchestrator/src/main/java/com/scottlogic/deg/orchestrator/generate/GenerateCommandLine.java, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/utils/CucumberGenerationConfigSource.java, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/endtoend/JarExecuteTests.java, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/endtoend/loadfiletest.profile.json, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/smoketest/TreeTransformationIntegrationTests.java, profile/src/main/java/com/scottlogic/deg/profile/guice/ProfileConfigSource.java, profile/src/main/java/com/scottlogic/deg/profile/guice/ProfileModule.java, profile/src/main/java/com/scottlogic/deg/profile/reader/CoreAtomicTypesConstraintReaderSource.java, profile/src/main/java/com/scottlogic/deg/profile/v0_1/AtomicConstraintType.java, profile/src/test/java/com/scottlogic/deg/profile/reader/BaseConstraintReaderMapTests.java, profile/src/test/java/com/scottlogic/deg/profile/reader/JsonProfileReaderTests.java
Enable specification of a root using the `--from-file-root` option.
Resolves #1060
=> Add option to change from file root

orchestrator/src/test/java/com/scottlogic/deg/orchestrator/endtoend/JarExecuteTests.java
tell people to run gradle build if the test fails
=> Add helpful message to jar execute tests

.circleci/config.yml, commit_check.sh, common/build.gradle, orchestrator/build.gradle
Enables automatic release and versioning.
- Checks commit messages adhere to the [angular format](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-format).
- Automatically creates a release for any merge to master.
- Calculates the new semantic version based on the commit messages provided.
**BEFORE MERGING, REQUIRES THE CIRCLECI SSH KEYS TO BE SETUP**
Resolves #701
=> 701: Automatic versioning and release

.circleci/config.yml
Update CI fingerprint
Resolves #701
=> fix(#701): Update CI key

.circleci/config.yml, .github/CONTRIBUTING.md, commit_check.sh
Update docs to represent usage of angular-style commit messages. Update checks to include all angular style message types.
Related to #701
=> Update commit message checks

generator/src/main/java/com/scottlogic/deg/generator/guice/DecisionTreeWalkerProvider.java, generator/src/main/java/com/scottlogic/deg/generator/guice/GeneratorModule.java, generator/src/main/java/com/scottlogic/deg/generator/walker/rowspec/CartesianProductRowSpecTreeSolver.java, generator/src/main/java/com/scottlogic/deg/generator/walker/rowspec/RowSpecDecisionTreeWalker.java, generator/src/main/java/com/scottlogic/deg/generator/walker/rowspec/RowSpecTreeSolver.java, generator/src/test/java/com/scottlogic/deg/generator/decisiontree/CartesianProductRowSpecTreeSolverTests.java
=> separate cartesian walker from rowspec consumption

profile/src/main/resources/profileschema/0.1/datahelix.schema.json
=> Improve error message when allOf or anyOf have fewer than two children

orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/grammatical/AllOf.feature
=> refactor(#91): Remove ignored test

generator/src/test/java/com/scottlogic/deg/generator/walker/decisionbased/DecisionBasedSolverTests.java
=> Added basic integration tests for the Decision Based Solver

generator/src/main/java/com/scottlogic/deg/generator/generation/string/ChecksummedCodeStringGenerator.java, generator/src/main/java/com/scottlogic/deg/generator/generation/string/CusipStringGenerator.java, generator/src/main/java/com/scottlogic/deg/generator/generation/string/RegexStringGenerator.java, generator/src/main/java/com/scottlogic/deg/generator/generation/string/SedolStringGenerator.java, generator/src/test/java/com/scottlogic/deg/generator/restrictions/TextualRestrictionsTests.java
=> fix(#1126) check if automaton is contradictory when merging string generators

docs/user/UserGuide.md, docs/user/gettingStarted/BuildAndRun.md
Corrects typos raised in #1170 
Resolves #1170
=> fix(#1170): Fix typos in documentation

README.md, docs/RoadMap.md
Simple brief document linked off main README page
=> docs(#1225): added first draft of roadmap to git hub

docs/developer/DeveloperGuide.md, docs/developer/GitMerging.md
=> Add first version of git merging docs

orchestrator/src/main/java/com/scottlogic/deg/orchestrator/generate/GenerateCommandLine.java, profile/src/main/java/com/scottlogic/deg/profile/reader/AtomicConstraintReader.java, profile/src/main/java/com/scottlogic/deg/profile/reader/AtomicConstraintTypeReaderMap.java, profile/src/main/java/com/scottlogic/deg/profile/reader/JsonProfileReader.java, profile/src/main/java/com/scottlogic/deg/profile/reader/MainConstraintReader.java, profile/src/main/java/com/scottlogic/deg/profile/reader/constraintreaders/EqualToFieldReader.java, profile/src/main/java/com/scottlogic/deg/profile/reader/constraintreaders/GranularToReader.java, profile/src/main/java/com/scottlogic/deg/profile/reader/constraintreaders/InSetReader.java, profile/src/main/java/com/scottlogic/deg/profile/reader/constraintreaders/OfTypeReader.java, profile/src/test/java/com/scottlogic/deg/profile/reader/AtomicConstraintReaderMapTests.java, profile/src/test/java/com/scottlogic/deg/profile/reader/JsonProfileReaderTests.java, profile/src/test/java/com/scottlogic/deg/profile/reader/constraintreaders/EqualToFieldReaderTest.java
separate interfaces of main constraint reader and subconstraint readers
replace complex mapping code with stream.map
=> refactor(#1209): slightly simplify structure of constraint readers

.circleci/config.yml
=> Revert "Remove Semantic Versioning"

.circleci/config.yml
Fix circleCI behaviour on gh-pages branch
=> Test simple inert CircleCI script

index.html
Updated broken links.
Updated Contributing section to reflect latest README.md
=> Updated broken links and Contributing section

README.md
docs#1249: update readme file
Update the Readme file following changes to the documentation
Add introduction with links to other documents
Add in The Problem, The Mission and The Product taken from the Vision doc in the wiki
Remove Contributing information
Related to #1249
=> 1249 - update readme.md

docs/DeveloperGuide.md
Corrected the links to other documents in the developer guide for contributing
=> docs(#1251): fixed links in developer guide

docs/DeveloperGuide.md, docs/GettingStarted.md
Links to User Guide were broken
Fixed the links
Related to #1252
=> 1252 fix link to user guide

docs/GettingStarted.md
Fixed developer guide links in getting started doc
=> docs(#0): fixed developer guide links in getting started doc

docs/DeveloperGuide.md, docs/developer/JUnitCookbook.md
As a team we felt there was a lack of clarity in the documentation about what was expected in terms of testing.
Split out the building and testing sections in the developer guide
Added some information to the testing section
Created a JUnit cookbook 
Added link to JUnit document
Related to #1242
=> 1242   add test strategy to dev guide

index.html, style.css, style.scss
https://godds.github.io/datahelix/
This probably isn't an ideal or long-term design to go with, but it's easily enough for now.
=> Simple responsive layout

README.md
=> Align "Contributing" section in README.md to FINOS project blueprint

orchestrator/build.gradle
This reverts commit 7fdca8e64cdd7d14c869e1ba487e96c5d3458b91.
=> revert(#1316): Append beta to release versions

examples/formatting/README.md
=> docs(#1298): Fix formatting in formatting example readme

common/src/main/java/com/scottlogic/deg/common/profile/constraintdetail/ParsedGranularity.java, profile/src/main/java/com/scottlogic/deg/profile/dto/ProfileSchemaValidatorLeadPony.java, profile/src/main/java/com/scottlogic/deg/profile/reader/atomic/AtomicConstraintValueReader.java, profile/src/main/java/com/scottlogic/deg/profile/reader/atomic/OfTypeConstraintFactory.java, profile/src/test/java/com/scottlogic/deg/profile/reader/atomic/OfTypeConstraintFactoryTest.java
A small refactor which came as a result of #1200.
Added some tests to the OfConstrainFactory
Fixed a link in an error message
Related to #1200
=> 1386 unit tests

profile/src/main/java/com/scottlogic/deg/profile/reader/JsonProfileReader.java, profile/src/test/java/com/scottlogic/deg/profile/reader/JsonProfileReaderTests.java
Corrected the parsing of the profile for inMap constraints. If the inMap constraint was nested in block then the internal field would not be created and the profile would fair during generation.
=> fix(#0): corrected parsing of nested inMap constraints

docs/DeveloperGuide.md
Updated developer guide documentation to make it clearer how to run the tests in the project.
=> docs(#0): Updated developer guide to clarify how to run tests

docs/developer/CucumberCookbook.md, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/ComplexProfiles.feature, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/ExhaustiveCombination.feature, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/general/InSet.feature, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/grammatical/AllOf.feature, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/grammatical/AnyOf.feature, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/grammatical/If.feature, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/temporal/DateTimeOtherField.feature, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/steps/DateValueStep.java, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/steps/GeneralTestStep.java, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/utils/CucumberTestState.java
Created cucumber hooks for the grammatical constraints (if, anyOf, and allOf) and updated the cucumber feature files to use these new hooks. 
Removed some redunent tests in the If.feature tests suite.
=> chore(#0): Added cucumber hooks for if, anyOf, and allOf

docs/UserGuide.md, examples/multiple-fileds/README.md, examples/multiple-fileds/profile.json
Added a little to the docs about command line arguments.
Added a section on combination strategy
Related to #1444
=> 1433 add cli options to docs

generator/src/main/java/com/scottlogic/deg/generator/profile/constraints/atomic/NotNullConstraint.java
Fix toString method in NotNullConstraint
=> chore(#0000): Fix toString method in NotNullConstraint

common/src/main/java/com/scottlogic/deg/common/profile/NumericGranularity.java
Random number generator was returning between max and max
Now returns between max and min
=> fix(#1478): random number generator to return random numbers

orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/general/InMap.feature, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/steps/GeneralTestStep.java, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/utils/CucumberTestHelper.java, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/utils/CucumberTestState.java, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/utils/InMemoryOutputTarget.java, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/utils/RowMatcher.java, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/utils/RowsAbsentMatcher.java, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/utils/RowsMatchAnyOrderMatcher.java, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/utils/RowsPresentMatcher.java
Changed cucumber test data rows from lists to maps
Resolves #1498
=> feat(#1498): Changed cucumber test data rows from lists to maps

common/src/test/java/com/scottlogic/deg/testUtils/TestRandomNumberGenerator.java, generator/src/test/java/com/scottlogic/deg/generator/generation/fieldvaluesources/datetime/DateTimeFieldValueSourceTests.java
Moves the TestRandomNumberGenerator into its own class and moves it to the common module
Related to #1381
=> Move TestRandomNumberGenerator out into common testUtils

.github/ISSUE_TEMPLATE/Feature_request.md, docs/developer/DefinitionOfReady.md
Update the Definition of Ready and the github new issue template.
Reduce the complexity of creating a new issue
=> chore(#0000): Update definition of Ready

docs/RoadMap.md
See #1514
Updated RoadMap.md for Q4 2019 milestone.  This includes mentioning that aiming for a V1 version and what that includes.  
Resolves #1514
=> (1514) Update RoadMap.md Q4 2019 milestone

common/src/main/java/com/scottlogic/deg/common/profile/DateTimeGranularity.java, common/src/main/java/com/scottlogic/deg/generator/utils/RandomNumberGenerator.java, common/src/test/java/com/scottlogic/deg/testUtils/TestRandomNumberGenerator.java, generator/src/main/java/com/scottlogic/deg/generator/generation/fieldvaluesources/LinearFieldValueSource.java, generator/src/main/java/com/scottlogic/deg/generator/utils/JavaUtilRandomNumberGenerator.java, generator/src/test/java/com/scottlogic/deg/generator/generation/fieldvaluesources/LinearFieldValueSourceTest.java, generator/src/test/java/com/scottlogic/deg/generator/generation/fieldvaluesources/datetime/DateTimeFieldValueSourceTests.java
Fixes upper bound values being missed during generation.
Resolves #1517
=> 1517 random upperbound functionality

generator/src/main/java/com/scottlogic/deg/generator/decisiontree/ConstraintNode.java, generator/src/main/java/com/scottlogic/deg/generator/decisiontree/DecisionNode.java, generator/src/main/java/com/scottlogic/deg/generator/fieldspecs/FieldSpec.java, generator/src/main/java/com/scottlogic/deg/generator/fieldspecs/RestrictionsMergeOperation.java, generator/src/main/java/com/scottlogic/deg/generator/generation/fieldvaluesources/NullOnlySource.java, generator/src/main/java/com/scottlogic/deg/generator/generation/string/AutomatonUtils.java, generator/src/main/java/com/scottlogic/deg/generator/generation/string/generators/StringGenerator.java, generator/src/main/java/com/scottlogic/deg/generator/guice/GeneratorModule.java, generator/src/main/java/com/scottlogic/deg/generator/restrictions/linear/Limit.java, generator/src/test/java/com/scottlogic/deg/generator/builders/TestConstraintNodeBuilder.java, generator/src/test/java/com/scottlogic/deg/generator/decisiontree/treepartitioning/TreePartitionerTests.java, generator/src/test/java/com/scottlogic/deg/generator/generation/VelocityMonitorTests.java, generator/src/test/java/com/scottlogic/deg/generator/generation/combinationstrategies/CombinationStrategyTester.java, generator/src/test/java/com/scottlogic/deg/generator/generation/fieldvaluesources/NullAppendingFieldValueSourceEqualityTests.java, generator/src/test/java/com/scottlogic/deg/generator/generation/string/AutomatonUtilsTests.java, generator/src/test/java/com/scottlogic/deg/generator/generation/string/CusipStringGeneratorTests.java, generator/src/test/java/com/scottlogic/deg/generator/generation/string/IsinStringGeneratorTests.java, generator/src/test/java/com/scottlogic/deg/generator/generation/string/SedolStringGeneratorTests.java, generator/src/test/java/com/scottlogic/deg/generator/restrictions/DateTimeRestrictionsMergerTests.java, generator/src/test/java/com/scottlogic/deg/generator/restrictions/DateTimeRestrictionsTests.java, generator/src/test/java/com/scottlogic/deg/generator/restrictions/StringRestrictionsMergerTests.java, generator/src/test/java/com/scottlogic/deg/generator/restrictions/TextualRestrictionsTests.java, orchestrator/src/main/java/com/scottlogic/deg/orchestrator/violate/ViolateModule.java, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/steps/JSONTestStep.java, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/steps/MapValueStep.java, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/utils/ListPredicateAnyTrueIsSuccessMatcher.java, orchestrator/src/test/java/com/scottlogic/deg/orchestrator/endtoend/JarExecuteTests.java, output/src/main/java/com/scottlogic/deg/output/guice/SingleDatasetOutputTargetProvider.java, profile/src/main/java/com/scottlogic/deg/profile/reader/handlers/CreateFieldsHandler.java
Removes unused imports.
Related to #1407
=> chore(#1407): Remove unused imports

common/src/main/java/com/scottlogic/datahelix/generator/common/profile/DateTimeGranularity.java, common/src/main/java/com/scottlogic/datahelix/generator/common/profile/NumericGranularity.java, common/src/main/java/com/scottlogic/datahelix/generator/common/profile/TimeGranularity.java, common/src/main/java/com/scottlogic/datahelix/generator/common/util/Defaults.java, common/src/main/java/com/scottlogic/datahelix/generator/common/util/defaults/DateTimeDefaults.java, common/src/main/java/com/scottlogic/datahelix/generator/common/util/defaults/NumericDefaults.java, common/src/main/java/com/scottlogic/datahelix/generator/common/util/defaults/TimeDefaults.java, core/src/main/java/com/scottlogic/datahelix/generator/core/restrictions/linear/LinearRestrictionsFactory.java, profile/src/main/java/com/scottlogic/datahelix/generator/profile/factories/relation_factories/DecimalRelationFactory.java, profile/src/main/java/com/scottlogic/datahelix/generator/profile/factories/relation_factories/IntegerRelationFactory.java, profile/src/main/java/com/scottlogic/datahelix/generator/profile/services/ConstraintService.java
- Added default granularity to constraints instead of null.
#1520 Still not solved due to #1489 
Related to #1520
=> Added default granularity

examples/generator/README.md, examples/generator/profile.json, orchestrator/src/test/java/com/scottlogic/datahelix/generator/orchestrator/validator/ProfileValidationTests.java, profile/src/main/java/com/scottlogic/datahelix/generator/profile/services/ConstraintService.java, profile/src/main/java/com/scottlogic/datahelix/generator/profile/validators/profile/ConstraintValidator.java, profile/src/test/java/com/scottlogic/datahelix/generator/profile/reader/JsonProfileReaderTests.java
- Added generator constraint creation to constraint service
Resolves #1488
=> feat(#1488): Added generator constraint

docs/GettingStarted.md, docs/UserGuide.md, docs/user/ProfileValidation.md
Cleanup / restructure the getting started guide
Move the vs code json validator to its own file
Fix title in docs
Update example profiles
Related to #1561 
Still todo on #1561 
- add links to datahelix UI
=> 1561 updating getting started guide

docs/GettingStarted.md
=> fix(#0000): Fix typo

docs/UserGuide.md
Changes the link for faker in the docs to point to the javadoc
=> docs(#0000): Update faker docs to point at the fakerapi docs

docs/GettingStarted.md, docs/user/ProfileValidation.md
Suggested changes to documentation.
I hope I did the semantic versioning thing right 🤞
=> docs(#0000): minor documentation updates

.whitesource
There are no changes to the actual file definition; this is just an update to trigger the bot to configure the scanning.
This should complete issue #1576
=> feat(#0001): trigger WhiteSource first scan

README.md
Some changes made to README.md at @ColinEberhardt 's request, to make it rather more concise and describe the project better.
=> docs(#0000): Improve README conciseness

index.html, playground/index.html, playground/style.css
- Fixed a couple of links
- Updated the navigation bar for consistency between the playground and the main site
=> Minor websites tweaks

docs/DeveloperGuide.md
Update the developer guide
Removes out of date information
=> 0000 update dev guide

README.md
This pull request is intended to increase the semver version number to v2.0.0 by merging from a release/2.0.0 branch
=> docs(#0000): Increase version number to 2.0.0

README.md
PR to update release version number.
=> docs(#0000): Release 2.0.0

ReleaseNotes.md
At @ColinEberhardt 's suggestion, I have added a manually-curated Release Notes file to contain details of major new features introduced in significant releases.
=> docs(#1591): Manually-curated release notes

.gitignore, .idea/.gitignore, .idea/runConfigurations/Example_generation__actorNames_.xml, .idea/runConfigurations/Example_generation__datetimeEqualToDynamicOffset_.xml, .idea/runConfigurations/Example_generation__faker_.xml, .idea/runConfigurations/Test_everything.xml
Adds a selection of example configurations to be used with intellij
=> chore(#0000): Add run configurations for intellij

.circleci/config.yml
@r-stuart please review; when merged, I will update the GH_TOKEN on https://circleci.com/gh/finos/datahelix/edit#env-vars
=> Using new build SSH keys managed by FINOS

.idea/runConfigurations/Example_generation__demo_.xml, examples/demo/README.md, examples/demo/profile.json
Introduce a more interesting example that can be showcased in the online playground
- New example
- New run configuration to execute example
- Another PR will be raised to make the playground default to this example once this PR has been merged.
Related to #1595
=> #1595: Add improved example

.idea/runConfigurations/Example_generation__actorNames_.xml, .idea/runConfigurations/Example_generation__datetimeEqualToDynamicOffset_.xml, .idea/runConfigurations/Example_generation__demo_.xml, .idea/runConfigurations/Example_generation__faker_.xml
Remove accidentally committed VM arguments
=> chore(#0000): Remove incorrectly introduced VM arguments

docs/DeveloperGuide.md
Add architectural principles to the developer guide.
=> Add architectural principles

index.html, streaming.css, streaming.js
Stream data on the home page.
Waits 1 second before requesting the first batch of data to prevent unnecessary data loads. Each subsequent batch will be requested when the current batch gets partly exhausted.
Streaming uses vanilla JavaScript rather than any other framework.
=> Stream data to home page

docs/developer/packaging/Chocolatey.md
Chocolatey documentation has an incorrect template for pushing packages to the repository
- Fix template in documentation
=> chore(#0000): Minor update to chocolatey documentation
