finos/datahelix

- generator/src/main/java/com/scottlogic/deg/generator/walker/reductive/FixedField.java
- generator/src/test/java/com/scottlogic/deg/generator/walker/reductive/FixedFieldTests.java
A fix to re-add the not null restriction when returning a set restriction for Fixed Fields
> Not Null Restriction for Set Restrictions in Fixed Fields

- .github/PULL_REQUEST_TEMPLATE.md
Add a PR template to the project so that every time we create a new PR we are prompted with some ideas on what would be useful to include in the description.
This is to help reviewers understand and review your code better and also to use as a reference as to why were changes made and how were they tested.
This change has not been tested. The expected behaviour is that once it is merged to master, any new PRs will have this template in their description:
https://help.github.com/articles/about-issue-and-pull-request-templates/
N/A.
> Add PR Template to the project

- generator/src/main/java/com/scottlogic/deg/generator/inputs/MainConstraintReader.java
- generator/src/test/java/com/scottlogic/deg/generator/inputs/ProfileReaderTests.java
When parsing the profile we want the generator to throw validation errors early as opposed to getting stuck half way through a profile. The "allOf" constraint should always contain constraints and hence this change will throw up a validation error if the JSON value is empty.
* Added empty check to ensure that AllOF constraint has at least one constraint inside.
* Added to ProfilerReaderTests.java to test new validation.
Resolves #424
> 424 - Add AllOf constraint validation

- generator/src/test/java/com/scottlogic/deg/generator/cucumber/MatchingRegex.feature
This change ignores a test in the cucumber framework which produces inconsistent results
> Ignore inconsistent test

- generator/src/main/java/com/scottlogic/deg/generator/fieldspecs/AtomicConstraintConstructTuple.java
- generator/src/main/java/com/scottlogic/deg/generator/fieldspecs/FieldSpecFactory.java
- generator/src/test/java/com/scottlogic/deg/generator/restrictions/FieldSpecFactoryTests.java
Adds a change to the FieldSpecFactory to optomise the construction of a Regex String generator
Creates a cache in the FieldSpecFactory to retrieve generators that have already been created with an associated atomic constraint.
Associated with #449
> Regex String Generator optimisation

- docs/EpistemicConstraints.md
- docs/FrequentlyAskedQuestions.md
- generator/src/main/java/com/scottlogic/deg/generator/constraints/atomic/MatchesStandardConstraint.java
- generator/src/main/java/com/scottlogic/deg/generator/constraints/atomic/StandardConstraintTypes.java
- generator/src/main/java/com/scottlogic/deg/generator/fieldspecs/FieldSpecFactory.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/IsinStringGenerator.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/SedolStringGenerator.java
- generator/src/main/java/com/scottlogic/deg/generator/inputs/AtomicConstraintReaderLookup.java
- generator/src/test/java/com/scottlogic/deg/generator/constraints/atomic/ContainsRegexConstraintTests.java
- generator/src/test/java/com/scottlogic/deg/generator/constraints/atomic/IsGranularToConstraintTests.java
- generator/src/test/java/com/scottlogic/deg/generator/constraints/atomic/IsInSetConstraintTests.java
- generator/src/test/java/com/scottlogic/deg/generator/constraints/grammatical/AndConstraintTests.java
- generator/src/test/java/com/scottlogic/deg/generator/constraints/grammatical/NotConstraintTests.java
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/AValid.feature
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/If.feature
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/MatchingRegex.feature
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/OfLength.feature
- generator/src/test/java/com/scottlogic/deg/generator/generation/IsinStringGeneratorTests.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/SedolStringGeneratorTests.java
- generator/src/test/java/com/scottlogic/deg/generator/inputs/AtomicConstraintReaderLookupTests.java
The `aValid` constraint when combined with other textual constraints throws an error.
- Don't throw an error when merging an `aValid` constraint with another textual constraint, instead emit no string values
- Updated documentation to cover this change, introduced FAQ to explain workable scenarios and link to issue created to implement a fix (#487)
- Fixed issues where negating an `aValid` had no effect, valid ISIN (and SEDOL) codes were still emitted, tests added
- Restored (un-ignored) tests that now pass due to this change
- Test classes moved to matching packages as in production module
- Refactored `MatchingStandardConstraint` to not hold onto a string generator, as per comment and to resolve negation issue
This is a 'temporary' fix to ensure that some data can be generated in these …
> aValid changes when merging with other textual constraints

- .github/CONTRIBUTING.md
Some links were incorrect in the CONTRIBUTING file. There was no clear indication of whether the `this` qualifier should be used or not. 
- Fix links to resources
- Introduce statement about `this` qualifier
- Introduce link to `Coding guidelines`
> Contributing updates

- generator/src/main/java/com/scottlogic/deg/generator/restrictions/DateTimeRestrictionsMerger.java
- generator/src/test/java/com/scottlogic/deg/generator/restrictions/DateTimeRestrictionsMergerTests.java
Includes a fix for when a contradictory before/after rule has been supplied to the profile which would still output the dates described in the rule. This PR also includes some extra tests since we didn't have any for the DateTimeRestrictionsMerger class
- A check in the DateTimeRestrictionsMerger to detect if the merged object contains an invalid date range
- Tests supporting the new functionality
- Tests for some of the existing functionality
Resolves #324
> Fix for contradictory before/after generating invalid dates

- docs/FrequentlyAskedQuestions.md
- generator/src/main/java/com/scottlogic/deg/generator/analysis/FieldDependencyAnalyser.java
- generator/src/main/java/com/scottlogic/deg/generator/decisiontree/MostProlificConstraintOptimiser.java
- generator/src/main/java/com/scottlogic/deg/generator/decisiontree/ProfileDecisionTreeFactory.java
- generator/src/main/java/com/scottlogic/deg/generator/decisiontree/TreeConstraintNode.java
- generator/src/main/java/com/scottlogic/deg/generator/decisiontree/TreeDecisionNode.java
- generator/src/main/java/com/scottlogic/deg/generator/decisiontree/tree_partitioning/ConstraintToFieldMapper.java
- generator/src/main/java/com/scottlogic/deg/generator/decisiontree/tree_partitioning/RelatedFieldTreePartitioner.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/StandardFieldValueSourceEvaluator.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/combination_strategies/ExhaustiveCombinationStrategy.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/combination_strategies/ReductiveCombinationStrategy.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/databags/ConcatenatingDataBagSource.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/databags/DataBag.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/field_value_sources/RealNumberFieldValueSource.java
- generator/src/main/java/com/scottlogic/deg/generator/outputs/CellSource.java
- generator/src/main/java/com/scottlogic/deg/generator/walker/CartesianProductDecisionTreeWalker.java
- generator/src/main/java/com/scottlogic/deg/generator/walker/reductive/field_selection_strategy/FieldAndConstraintMapping.java
- generator/src/main/java/com/scottlogic/deg/generator/walker/reductive/field_selection_strategy/SetBasedFixFieldStrategy.java
The `flatMap` implementation in the JDK will prevent any data being emitted until all data points have been calculated. In RANDOM mode the input to `flatMap` is an infinite stream (the row-limits are applied at a later stage) as such the stream never completes.
- Use the `flatMap` shim (workaround) as widely as possible **to save falling into this trap in the future**
- Some uses of `flatMap` have not been changed as they would require further changes to allow their use
No expected change in behaviour is expected
Manually tested and able to produce data with the following command (which otherwise fails on `master`)
`generate -n 100 -t random -w reductive "names-profile.json" "names-profile.csv"`
where `names-profile.json` can be created from #466 
Resolves #466 
Resolves #68
> Use flatMap shim as widely as possible

- generator/src/test/java/com/scottlogic/deg/generator/generation/RegexStringGeneratorTests.java
A `RegexStringGenerator` test is failing it wasn't spotted due to #556 
- Fixed test to ensure `hasNext()` is called before `next()` as is the contract with an `Iterator`
- Using `Stream`s for a more indicative test of how the output would be used.
- No functional change
Raises a bigger question of why do we use/expose `Iterator`s rather than `Stream`s which would have prevented/highlighted this issue earlier.
Resolves #557
> Test fixes: RegexStringGenerator

- generator/pom.xml
- pom.xml
- schemas/pom.xml
Fix `pom.xml` files to run all tests.
junit 4 and junit 5 tests are now run when `mvn test` is executed.
resolves #536
> fixed `pom.xml` files so that unit and integration tests are run.

- generator/src/main/java/com/scottlogic/deg/generator/generation/RegexStringGenerator.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/RegexStringGeneratorTests.java
During investigation of Random data generation, it was discovered that invalid Unicode (surrogates) characters would be generated if the generation mode was set to RANDOM
brought function `isStringValidUtf8(String)` out of inner class up into parent class.
created function `isCharValidUtf8(char)`
call `isCharValidUtf8(char)` from `RegexStringGenerator.generateRandomStringInternal()`
Resolves #526
> Bug 526 regex random invalid unicode chars

- docs/Options/GenerateOptions.md
- generator/src/main/java/com/scottlogic/deg/generator/CommandLine/GenerateCommandLine.java
- generator/src/main/java/com/scottlogic/deg/generator/Guice/BaseModule.java
- generator/src/main/java/com/scottlogic/deg/generator/Guice/IterationVisualiserProvider.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/GenerationConfigSource.java
- generator/src/main/java/com/scottlogic/deg/generator/walker/reductive/ReductiveIterationVisualiser.java
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/utils/CucumberGenerationConfigSource.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/TestGenerationConfigSource.java
1. The reductive iteration visualiser didn't work with violations and normal generation in equal measure
1. The reductive iteration visualiser couldn't be enabled without recompiling the code
1. Reductive iteration visualiser now works when violating (directory output path) and when not-violating (file output path)
1. Reductive iteration visualiser can be enabled via the command line (--visualise-reductions)
- @harryBedfordSL / @EllieHield the mind-map for UX should be updated with this switch - #548 
Resolves #560
> Fixes for reductive iteration visualiser

- generator/src/main/java/com/scottlogic/deg/generator/outputs/dataset_writers/SourceTracingDataSetWriter.java
- generator/src/main/java/com/scottlogic/deg/generator/outputs/targets/FileOutputTarget.java
- Fixed `--trace-constraints` option
- added regex replace all to trim file extensions from output file names before generating -trace.json file name 
- added directory resolution to ensure file is outputted on file path specified not working directory
Resolves #569
> 569 Fix Trace Constraints Filename Error 

- docs/Options/GenerateOptions.md
- generator/docs/TracingOutput.md
- generator/src/main/java/com/scottlogic/deg/generator/CommandLine/GenerateCommandLine.java
Clarified some contradictory documentation around generate options. Added description to generate picocli instructions.
- Removed outdated statement about `--trace-constraints` not being configurable
- Corrected contradictory information about the file produced by `--trace-constraints`
- Added full worded options to generate options where they were missing 
- Added an encompassing description to the generate command line picocli instructions which appear when generate with no arguments is specified
Resolves #548
> 548 documentation correction and CL clarifying 

- generator/src/main/java/com/scottlogic/deg/generator/Guice/BaseModule.java
- generator/src/main/java/com/scottlogic/deg/generator/Guice/ProfileProvider.java
- generator/src/main/java/com/scottlogic/deg/generator/walker/reductive/field_selection_strategy/HierarchicalDependencyFixFieldStrategy.java
- generator/src/main/java/com/scottlogic/deg/generator/walker/reductive/field_selection_strategy/ProfileBasedFixFieldStrategy.java
- generator/src/main/java/com/scottlogic/deg/generator/walker/reductive/field_selection_strategy/SetBasedFixFieldStrategy.java
- generator/src/test/java/com/scottlogic/deg/generator/Guice/ProfileProviderTests.java
- generator/src/test/java/com/scottlogic/deg/generator/walker/reductive/field_selection_strategy/TestHierarchicalDependencyFixFieldStrategy.java
Before this change the `Profile` itself was being injected into classes where it was used. This caused a Guice provisioning error at run time whenever the `profile` was invalid. Now, the `profileProvider` is injected into the classes where a profile needed. This ensures Guice can always provision the dependency, and an exception is only thrown due to an error in reading the profile.
- `profileProvider` now injected instead of `Profile` where needed
- `profileProvider` updated to store the profile itself, meaning that reading the profile only occurs once
- Unit tests added for `profileProvider` functionality
- Fixed `TestHierarchicalDependencyFixFieldStrategy.java` to use `profileProver` instead of `profile` when newing up the strategy
Passing the profile throw method arguments was …
> 577 Profile injection

- generator/src/main/java/com/scottlogic/deg/generator/CommandLine/GenerateCommandLine.java
- generator/src/main/java/com/scottlogic/deg/generator/Visualise.java
Updating the visualise and generate command line options to display in a consistent format. 
- changed visualise to require a file path not a directory path to be consistent with generate
- removed tree partitioning in visualise
- --version removed
- --help added as an option
- changed vocabulary to match 
Resolves #576
> 576 consistency refactor

- docs/Options/GenerateOptions.md
- docs/Options/VisualiseOptions.md
- generator/src/main/java/com/scottlogic/deg/generator/CommandLine/GenerateCommandLine.java
Made picocli commands more consistent and updated options documentation.
- Removed single letter double dash option switches (i.e. only allow -t not --t)
- Updated documentation to reflect this and make consistent throughout
Resolves #580
> 580 picocli consistency

- .gitignore
- docs/Options/GenerateOptions.md
- generator/pom.xml
- generator/src/main/java/com/scottlogic/deg/generator/CommandLine/GenerateCommandLine.java
- generator/src/main/java/com/scottlogic/deg/generator/GenerateExecute.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/GenerationConfigSource.java
- generator/src/main/java/com/scottlogic/deg/generator/outputs/targets/FileOutputTarget.java
- generator/src/main/java/com/scottlogic/deg/generator/utils/FileUtils.java
- generator/src/main/java/com/scottlogic/deg/generator/validators/GenerationConfigValidator.java
- generator/src/test/java/com/scottlogic/deg/generator/GenerateExecuteTests.java
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/utils/CucumberGenerationConfigSource.java
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/utils/InMemoryOutputTarget.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/TestGenerationConfigSource.java
- generator/src/test/java/com/scottlogic/deg/generator/validators/GenerationConfigValidatorTests.java
- pom.xml
test for overwriting an existing file
* Update `GenerationConfigValidator` to check for whether the output file already exists and return an error if it does.
* added `--overwrite` command line option
* add tests to `GenerationConfigValidatorTests`
Resolves #566
> issue #566 - Add check for overwriting output files

- generator/src/main/java/com/scottlogic/deg/generator/Guice/BaseModule.java
- generator/src/main/java/com/scottlogic/deg/generator/inputs/IndividualRuleProfileViolator.java
- generator/src/main/java/com/scottlogic/deg/generator/inputs/ProfileViolator.java
- generator/src/main/java/com/scottlogic/deg/generator/outputs/manifest/JsonManifestWriter.java
- generator/src/main/java/com/scottlogic/deg/generator/outputs/manifest/ManifestWriter.java
- generator/src/main/java/com/scottlogic/deg/generator/outputs/manifest/ManifestWriterImpl.java
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/utils/CucumberManifestWriter.java
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/utils/CucumberTestModule.java
- generator/src/test/java/com/scottlogic/deg/generator/inputs/IndividualRuleProfileViolatorTests.java
- generator/src/test/java/com/scottlogic/deg/generator/smoke_tests/ExampleProfilesViolationTests.java
Update code to throw IOException if it is unable to write the `manifest.json` file.
refactor `ManifestWriter` into an interface and use Guice to inject it into code and tests.
Resolves #627
> 627 abort if unable to write manifest.json file

- generator/src/test/java/com/scottlogic/deg/generator/cucumber/ShorterThan.feature
Some of our cucumber tests are running slower than they can, incurring time delays and additional compute costs for each pull request check
- Change each identified scenario in #596 to produce less data
- Updated unaffected scenario to reference related ticket explaining why its ignored
- All cucumber 937 scenarios run and pass in following times: 10.251s, 10.270s, 9.412s, 9.117s, 8.995s - avg: ~9.6s
- All 1665 tests for the generator run and pass in 11.672s, 10.35s, 10.642s - avg: ~10.9s
- `ShorterThan.feature` is the only affected file
Resolves #596
> 596- cucumber test performance

- generator/src/main/java/com/scottlogic/deg/generator/GenerateExecute.java
- generator/src/main/java/com/scottlogic/deg/generator/Guice/BaseModule.java
- generator/src/main/java/com/scottlogic/deg/generator/utils/FileUtils.java
- generator/src/main/java/com/scottlogic/deg/generator/validators/ConfigValidator.java
- generator/src/main/java/com/scottlogic/deg/generator/validators/GenerationConfigValidator.java
- generator/src/test/java/com/scottlogic/deg/generator/GenerateExecuteTests.java
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/utils/CucumberGenerationConfigValidator.java
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/utils/CucumberTestModule.java
- generator/src/test/java/com/scottlogic/deg/generator/validators/GenerationConfigValidatorTests.java
Added checks to the `GenerationConfigValidator` for the profile file to prevent the Google Guice provisioning errors.
- Added Pre Profile Checks for: 
- Profile file not existing
- Profile file path containing invalid chars
- Profile file path pointing to a directory
- Profile file having no content
- Profile file having non json content
- Added `ConfigValidator` interface to aid with cucumber testing and to allow for future config validators to be added 
- Refactored `GenerationConfigValidator` slightly including renaming methods for clarity
- Added tests
- Renamed existing tests to follow suggested  naming convention
Resolves #567
> 567 remove provisioning errors

- generator/src/main/java/com/scottlogic/deg/generator/utils/FileUtils.java
- generator/src/main/java/com/scottlogic/deg/generator/validators/GenerationConfigValidator.java
- generator/src/test/java/com/scottlogic/deg/generator/validators/GenerationConfigValidatorTests.java
Automatically create output directory for violation
Fix creating directory when any part of the path is a pre-existing file
Resolves #637
> create output directory for violation

- .github/ISSUE_TEMPLATE/Bug_report.md
Bug label is often missed from bug reports, [GitHub supports](https://help.github.com/en/articles/about-automation-for-issues-and-pull-requests-with-query-parameters#supported-query-parameters) the definition of default labels per issue type/template.
- Set `bug` as a default label for bug reports
Not related to an issue
> Include bug label by default for bugs

- generator/src/main/java/com/scottlogic/deg/generator/generation/combinationstrategies/ExhaustiveCombinationStrategy.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/combinationstrategies/PinningCombinationStrategy.java
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/GreaterThan.feature
Some tests in the `GreaterThan.feature` file fail intermittently.
- Remove parallel stream processing to provide more consistency in the output
- GreaterThan.feature (1.6s-1.8s - 3 samples) vs (1.8s-2.3s - 3 samples) [original]
- All tests (12.6s-13.7s - 3 samples) vs (12.6s-13.2s - 3 samples) [original]
Resolves #680
> 680- Remove parallel combination for output consistency

- examples/a-valid-isin/profile.json
- examples/actor-names/profile.json
- examples/date-equal-to/profile.json
- examples/duplicates/profile.json
- examples/formatting-integer/profile.json
- examples/integer-range-with-blacklist/profile.json
- examples/integer-range/profile.json
- examples/partitioning/profile.json
- examples/real-number-range/profile.json
- examples/regex-contains/profile.json
- examples/regex-intersect-with-blacklist/profile.json
- examples/regex-intersect/profile.json
- examples/regex/profile.json
- examples/setwise-combination/profile.json
- examples/shorter-than/profile.json
- examples/type-exclusion/profile.json
- generator/src/test/java/com/scottlogic/deg/generator/smoke_tests/ExampleProfilesViolationTests.java
Example files are not correctly formed, and this correctness was not asserted before. In additional all smoke tests over these files only exercised the violating generator, not the _normal_ generator.
- Update smoke tests to test both violating and _normal_ generators (as original designed)
- Introduced checks to prove correctness of example files (i.e. every rule must have at least one constraint in the examples)
All tests run and pass in ~13.5s
Resolves #715
> 715- fixes for smoke tests over example profiles

- generator/src/test/java/com/scottlogic/deg/generator/cucumber/ContainingRegex.feature
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/ShorterThan.feature
Resolves #686 
- Restructure of shorterThan tests in line with test matrix to remove duplicates
- Standardisation of indenting in line with guidelines on wiki [https://github.com/ScottLogic/datahelix/wiki/Using-the-Cucumber-framework](url)
> #686 dedupe shorter than ci

- generator/src/main/java/com/scottlogic/deg/generator/generation/fieldvaluesources/TemporalFieldValueSource.java
- generator/src/main/java/com/scottlogic/deg/generator/utils/JavaUtilRandomNumberGenerator.java
- generator/src/main/java/com/scottlogic/deg/generator/utils/RandomNumberGenerator.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/fieldvaluesources/TemporalFieldValueSourceTests.java
Temporal values are emitted in a small range when random mode is enabled, this fix unifies the ranges to the document (if #636) range.
- Set production of random values to produce between _0001-01-01T00:00:00_ and _9999-12-31T23:59:59.999_ **inclusively**
- Introduced tests for change of behaviour, extended existing tests for additionally considered scenarios
- Fixed max range to be 999,000,000 nanoseconds (i.e. 999 milliseconds), rather than 999 nanoseconds
- Implementation detail: Updated random interface to clarify that decimal bounds are inclusive and exclusive as appropriate.
No cucumber scenarios exist for random at present, but will be covered in #719 and #720.
All tests run and pass in 11.635s
Resolves #695
> 695- random temporal range fix

- generator/src/main/java/com/scottlogic/deg/generator/fieldspecs/DateTimeRestrictionsMergeOperation.java
- generator/src/main/java/com/scottlogic/deg/generator/fieldspecs/FieldSpecMerger.java
- generator/src/main/java/com/scottlogic/deg/generator/fieldspecs/NumericRestrictionsMergeOperation.java
- generator/src/main/java/com/scottlogic/deg/generator/inputs/validation/validators/TemporalConstraintValidator.java
- generator/src/main/java/com/scottlogic/deg/generator/restrictions/DataTypeRestrictions.java
- generator/src/main/java/com/scottlogic/deg/generator/restrictions/DateTimeRestrictionsMerger.java
- generator/src/main/java/com/scottlogic/deg/generator/restrictions/NumericRestrictionsMerger.java
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/After.feature
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/Before.feature
- generator/src/test/java/com/scottlogic/deg/generator/fieldspecs/DateTimeRestrictionsMergeOperationTests.java
- generator/src/test/java/com/scottlogic/deg/generator/fieldspecs/NumericRestrictionsMergeOperationTests.java
- generator/src/test/java/com/scottlogic/deg/generator/restrictions/DataTypeRestrictionsTests.java
- generator/src/test/java/com/scottlogic/deg/generator/restrictions/DateTimeRestrictionsMergerTests.java
- generator/src/test/java/com/scottlogic/deg/generator/restrictions/NumericRestrictionsMergerTests.java
DateTime restriction merging would permit all temporal values if contradicting restrictions were found.
When checking the above, it was found that Numeric restrictions did not check for contradictions, this has been aligned to mirror the changes for DateTime merging.
- If a DateTime range contradiction is found, prevent any production of temporal values
- Check for contradictions with numeric ranges
- If a Numeric range contradiction is found, prevent any production of string values
- Introduction of tests for both DateTime and Numeric mergers and their merge-operations
- Scenario where bug was identified un-ignored in Before.feature
All tests run and pass in 12.8s-13.8s (3 runs) - as at 08/03/2019
Resolves #635 
Resolves #673
> 635- datetime & numeric merge fixes

- README.md
- docs/Options/GenerateOptions.md
- docs/Options/VisualiseOptions.md
- generator/docs/GenerationTypes.md
- generator/src/main/java/com/scottlogic/deg/generator/App.java
- generator/src/main/java/com/scottlogic/deg/generator/commandline/GenerateCommandLine.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/GenerationConfig.java
- generator/src/main/java/com/scottlogic/deg/generator/validators/GenerationConfigValidator.java
- generator/src/test/java/com/scottlogic/deg/generator/validators/GenerationConfigValidatorTests.java
Tidy-up process of aligning our documentation with PicoCli help and the reverse.
All tests run and pass in 12.481s
Resolves #714
> 714- command line changes

- generator/src/test/java/com/scottlogic/deg/generator/cucumber/ContainingRegex.feature
Fix to 2x scenarios in containing regex.
> Fix regex anchor tests to remove duplicate Foo field setup which caued test failure.

- docs/CucumberSyntax.md
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/steps/DateValueStep.java
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/steps/GeneralTestStep.java
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/steps/NumericValueStep.java
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/steps/RegexValueStep.java
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/steps/StringValueStep.java
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/utils/CucumberTestHelper.java
Cucumber steps only support a limited number of data characteristic checks, this pull request introduces more.
- Introduced regex matching/not-matching checks
- Introduced not-within (i.e. outside) range checks for numeric, temporal and string-lengths
- Introduced before/less/shorter than or equal checks for temporal, numeric and strings as appropriate
- Introduced after/more/longer than or equal checks for temporal, numeric and strings as appropriate
- Updated documentation to describe changes
- Fix for #719- number of rows generated step
Resolves #720
> 720- additional cucumbers steps for random

- generator/src/test/java/com/scottlogic/deg/generator/cucumber/steps/DateValueStep.java
Date regular expression for cucumber steps includes a `$` anchor, meaning all dates need to be at the end of a step. The changes for #719 require dates to be permitted anywhere in a step
- Removal to `$` anchor to permit dates within the content (not just at the end) of a step
Was previously working, but regressed as part of fb8f7f4
Relates to #719
> 719- fix for date regex in cucumber

- .travis.yml
Configuration for travis-ci if this becomes the CI tool for this project. The reporting on failing unit tests doesn't match Circle CI so it won't be used.
Travis CI is connected to the project but is currently turned off.
> 702- added travis ci file

- docs/Options/GenerateOptions.md
Fix typo in documentation
* Corrected "ofType" to "typeOf" in generation docs
> Correct typo in generate documentation

- generator/src/main/java/com/scottlogic/deg/generator/restrictions/DateTimeRestrictions.java
- generator/src/main/java/com/scottlogic/deg/generator/restrictions/DateTimeRestrictionsMerger.java
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/After.feature
- generator/src/test/java/com/scottlogic/deg/generator/restrictions/DateTimeRestrictionsMergerTests.java
- generator/src/test/java/com/scottlogic/deg/generator/restrictions/DateTimeRestrictionsTests.java
Currently temporal constraints that contradict allows for one value to be created where it shouldn't. See #672 for further detail. This change updates the contradiction checking to be more thorough to prevent this circumstance.
- Update contradiction checking to take into account exclusive ranges (i.e. after/before vs afterOrAt/beforeOrAt - which are inclusive)
- Introduced new unit tests for changed logic, see `DateTimeRestrictionsTests`, which test `DateTimeLimit`.
- Unignored previously ignored cucumber scenarios
Branched off #611 to prevent merge conflicts in future, requires #611 to be merged first.
The following tests have been added:
| min | max | expected & actual |
| ---- | ---- | ---- |
| > 1900-01-01 | <= 1900-01-01 | contradiction |
| > 1900-01-01 | < 1900-01-01 | …
> 672 contradictory temporal fixes

- generator/src/main/java/com/scottlogic/deg/generator/generation/GenerationConfig.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/fieldvaluesources/RealNumberFieldValueSource.java
- generator/src/main/java/com/scottlogic/deg/generator/inputs/AtomicConstraintReaderLookup.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/fieldvaluesources/RealNumberFieldValueSourceTests.java
- generator/src/test/java/com/scottlogic/deg/generator/inputs/AtomicConstraintReaderLookupTests.java
- schemas/src/main/resources/profileschema/0.1/datahelix.schema.json
- schemas/src/test/java/com/scottlogic/deg/schemas/v0_1/ProfileValidatorTests.java
- schemas/src/test/resources/test-profiles/profile-test-greaterThan-max-errors.json
- schemas/src/test/resources/test-profiles/profile-test-greaterThan-max.json
- schemas/src/test/resources/test-profiles/profile-test-greaterThanOrEqualTo-max-errors.json
- schemas/src/test/resources/test-profiles/profile-test-greaterThanOrEqualTo-max.json
- schemas/src/test/resources/test-profiles/profile-test-lessThan-min-errors.json
- schemas/src/test/resources/test-profiles/profile-test-lessThan-min.json
- schemas/src/test/resources/test-profiles/profile-test-lessThanOrEqualTo-min-errors.json
- schemas/src/test/resources/test-profiles/profile-test-lessThanOrEqualTo-min.json
Introduce a "sensible" maximum and minimum for numeric values to be +/-1E20, respectively.
- Place new `MAX` and `MIN` values in the `GenerationConfig`
- Made new exception if number is out of the min max bounds
- Added a guard to further prevent numbers larger/smaller than the min/max to make it through to generation
- Updated the schema to also check when the user is writing their profile
Resolves #707
> 707 - Sensible numeric max min

- generator/src/main/java/com/scottlogic/deg/generator/generation/VelocityMonitor.java
Violate mode with multiple rules did not work.
A new time is made on every generation run in the velocity monitor.
Resolves #818
> 818 - Create new timer each generation

- examples/hard-contradiction-range-and-granular/README.md
- examples/hard-contradiction-range-and-granular/profile.json
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/Contradictions.feature
Covers the situation where the type is integer but the value is less than 1 and greater than 0
Added profile and test.
Moves location of `Contradictions.feature`
Related to #817
> 817- Added cucumber test and profile for a hard contradiction

- generator/src/main/java/com/scottlogic/deg/generator/fieldspecs/SetRestrictionsMergeOperation.java
- generator/src/main/java/com/scottlogic/deg/generator/restrictions/GranularityRestrictions.java
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/features/operators/InSet.feature
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/features/operators/Null.feature
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/features/types/Integer.feature
Granular to constraints were not being checked against inSet constraints. i.e. previously, granular to 1 and in Set [1.2] would generate 1.2. This PR changes this so that no contradicting data is generated.
- Added `isCorrectScale` method to granularToRestrcitions to check the scale of a numeric value from a set is correct
- Unignored cucumber scenarios relating to issues
Found new bug related to granular to, #824 
Resolves #795 
Resolves #677
> 795 granular to works with in sets

- .github/ISSUE_TEMPLATE/Bug_report.md
Automatically assign bugs to the bug-board, will go into the 'To Triage' column by default.
> Add bugs to the 'bug board' automatically

- generator/src/main/java/com/scottlogic/deg/generator/commandline/GenerateCommandLine.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/GenerationConfigSource.java
- generator/src/main/java/com/scottlogic/deg/generator/guice/ProfileValidatorProvider.java
- generator/src/main/java/com/scottlogic/deg/generator/inputs/validation/MultipleProfileValidator.java
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/testframework/utils/CucumberGenerationConfigSource.java
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/testframework/utils/CucumberTestState.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/TestGenerationConfigSource.java
Type mandatoriness (mandation) changes are on by default and there is no means to disable them. This change allows for this process to be disabled via a command line interface (CLI) switch.
- Introduce CLI switch --allow-untyped-fields
- Only include the 'type mandatoriness' validator if the CLI switch isn't provided
Resolves #768
> 768- Allow fields to be untyped via a CLI switch

- generator/src/main/java/com/scottlogic/deg/generator/generation/fieldvaluesources/RealNumberFieldValueSource.java
- generator/src/main/java/com/scottlogic/deg/generator/utils/JavaUtilRandomNumberGenerator.java
- generator/src/main/java/com/scottlogic/deg/generator/utils/RandomNumberGenerator.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/fieldvaluesources/datetime/DateTimeFieldValueSourceTests.java
when using double for random generation of large numbers
it lost precision and generated only integers.
Created nextBigDecimal method for use in random.
it uses bigDecimal, so does not lose precision
Resolves #850
> create getBigDecimal for random

- generator/src/main/java/com/scottlogic/deg/generator/restrictions/NumericRestrictions.java
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/features/operators/InSet.feature
Scale wasn't being checked properly, 2.0 didn't count as an integer
strip trailing zeros when checking scale
enable test
Resolves #824
> strip trailing zeros when checking scale

- generator/src/main/java/com/scottlogic/deg/generator/GenerateExecute.java
- generator/src/main/java/com/scottlogic/deg/generator/validators/ErrorReporter.java
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/testframework/utils/CucumberErrorReporter.java
- generator/src/test/java/com/scottlogic/deg/generator/cucumber/testframework/utils/CucumberTestModule.java
When running cucumber features, any unhandled exception (or invalid profile exceptions) are printed to the output, polluting the display. This pull request ensures these exceptions are captured and no longer pollute the output.
- Ensure thrown exceptions are captured and can be asserted against
- Ensure thrown exceptions do not get printed to output when running via Cucumber
- Error reporter will still emit the error details in 'run' mode, as before - no change to behaviour
Resolves #863
> 863- Hide exception output during cucumber runs

- generator/src/main/java/com/scottlogic/deg/generator/walker/ReductiveDecisionTreeWalker.java
- generator/src/main/java/com/scottlogic/deg/generator/walker/reductive/ReductiveState.java
show useful description for visualise reductions
fix tostring in reductive state
call next reductive state rather than previous, when visualising
Resolves #885
> 885 fix visualise reductions

- .circleci/config.yml
- .codecov.yml
Cover coverage previously provided detail of test results; however added confusion by including comments in PRs, so it was disabled. This change re-enables the reporting, but disables the introduction of comments on the PR.
- Re-enable Codecov
- Ensure comments aren't added to PRs
> Re-enable code coverage reports

- docs/GeneratorDeveloperGuide.md
Contributing link is case sensitive and currently leads to page not found/404. Updated to link to the correct page.
Unit testing link leads to cucumber syntax guide - this is not unit testing so adjusted wording to integration testing.
> Fixes to Developer Guide

- docs/ProfileDeveloperGuide.md
This information is already provided for datetime - now present for all types.
> Add string length, numeric range in Profile Developer Guide

- generator/src/test/java/com/scottlogic/deg/generator/fieldspecs/FieldSpecTests.java
Some exceptions used are implementation details of the most used JDK, and not defined in the JDK specification.
- Change sun not implemented exceptions to JDK standard defined exceptions.
> Remove sun specific exception

- generator/src/main/java/com/scottlogic/deg/generator/generation/RegexStringGenerator.java
This code is already dubious:
```
try {
String shortestString = AutomatonUtils.getShortestExample(automaton);
String longestString = AutomatonUtils.getLongestExample(automaton);
return shortestString.equals(longestString)
? Collections.singleton(shortestString)
: Arrays.asList(shortestString, longestString);
} catch (Exception e) {
System.out.println(
String.format(
"Unable to generate interesting strings for %s\n%s",
this.regexRepresentation,
e.getMessage()));
return Collections.emptySet();
}
```
but replacing `System.out` with `System.err` makes it 5% less dubious and removes a case where it could foul up generating to stdout (see #440).
> Make RegexStringGenerator print to stderr instead of stdout

- generator/src/main/java/com/scottlogic/deg/generator/generation/DataGeneratorMonitor.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/MessagePrintingDataGeneratorMonitor.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/NoopDataGeneratorMonitor.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/ReductiveDataGeneratorMonitor.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/VelocityMonitor.java
- generator/src/main/java/com/scottlogic/deg/generator/guice/BaseModule.java
- generator/src/main/java/com/scottlogic/deg/generator/guice/MonitorProvider.java
Some monitors print to stdout. Prior to this change, they directly reference `System.out`. This change makes them consume a PrintWriter, so they can (separately to this change) write to stderr instead in the case where stdout is being used for streaming generated data.
> Make monitors destination-agnostic

- generator/src/main/java/com/scottlogic/deg/generator/inputs/validation/MultipleProfileValidator.java
- generator/src/main/java/com/scottlogic/deg/generator/restrictions/DataTypeRestrictions.java
- generator/src/test/java/com/scottlogic/deg/generator/restrictions/DataTypeRestrictionsTests.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/Violation.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/grammatical/AllOf.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/steps/GeneralTestStep.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/utils/CucumberGenerationConfigSource.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/utils/CucumberTestHelper.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/utils/CucumberTestModule.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/utils/CucumberTestState.java
- Removed "micro-optimisation" which was optimising incorrectly in some cases.
- Removed broken code.
- Added unit tests.
- Added cucumber tests.
- Added cucumber construct "untyped fields are allowed" to emulate --allow-untyped-fields.
- Adds a constructor for MultipleProfileValidator purely for testing, so there might be a better way to do this.
- Adds a conditional binding for test instances of ProfileValidator. There might be a better way to do this.
Resolves #1006 
Resolves #981
> Fixed bug with allOf and added support for --allow-untyped-fields in cucumber

- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/steps/GeneralTestStep.java
Just a minor change to allow use of singular grammar as well as plural for a couple of steps - so if you wanted a step to check a single row was generated you could now use step `Then 1 row of data is generated` instead of the previous `Then 1 rows of data are generated` or if you wanted to generate max 1 row you could write `Given the generator can generate at most 1 row` instead of  `Given the generator can generate at most 1 rows`.
> Update step definitions to allow use of singular nouns

- Dockerfile
- docker-build.sh
Added Dockerfile that builds DataHelix inside its own docker environment and generates a docker container that only contains the fatJar executable and the Java 8 JRE.
I did this to make sure I could build this without messing up my local machine but I thought it might be useful to include in the project.
This Dockerfile provides an executable definition of how to build DataHelix and produces a self-contained executable Docker image which might (in some cases) be an easier alternative for running DataHelix without having to install a JRE.
It just adds the files `docker-build.sh` which is a shell script which builds the Dockerfile and `Dockerfile` the docker image definition to build.
Once built you can run the image with:
```shell
docker run -ti -v mydir:/data datahelix [parameters]
``` …
> Added Dockerfile that builds DataHelix inside its own docker env

- .circleci/config.yml
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/endtoend/JarExecuteTests.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/endtoend/testprofile.profile.json
This test simply runs the generator from the jar and checks that a single line from a simple profile is generated correctly. Only tests STDOUT, not csv generation. 
After much messing around with the path it now works both locally and on CircleCI!
If there is a better way of doing this than ProcessBuilder then let me know. In future this could be expanded to test more things but the intention of this one test is mostly just to check jar generation isn't completely broken rather than to test generator features which is left to cucumber. The next step might be to check command line options are applied as this is currently not tested in cucumber.
> Add basic Jar/E2E test

- README.md
- docs/FrequentlyAskedQuestions.md
- docs/GettingStarted/GeneratingData.md
- docs/GettingStarted/Visualise.md
- docs/Options/GenerateOptions.md
- docs/Options/ViolateOptions.md
- docs/Options/VisualiseOptions.md
- docs/ProfileDeveloperGuide.md
- generator/docs/GeneratorSetup.md
Since merging the stdout feature, the Markdown documents have largely had incorrect syntax on their command-line examples
* Update example command lines
* Include documentation of the `--profile-file` and `--output-path` options.
> Update documentation to include stdout feature

- generator/docs/GeneratorSetup.md
The commands given in the documentation are still in the positional format and no longer work
> Update documentation to use new command format

- orchestrator/build.gradle
Gradle task `orchestrator:test` is now dependent on fatJar and so will build the jar file if necessary. This prevents JarExecuteTests from failing if the jar has not previously been built.
> Add dependency to test task in build.gradle

- common/src/main/java/com/scottlogic/deg/common/profile/ProfileFields.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/DecisionTreeDataGenerator.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/UpfrontTreePruner.java
- generator/src/main/java/com/scottlogic/deg/generator/walker/reductive/ReductiveTreePruner.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/DecisionTreeDataGeneratorTests.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/UpfrontTreePrunerTests.java
- Pruner called on full tree at start of generation.
- Generation will terminate early if the profile is wholly contradictory and will not try to optimise.
- Unit tests added.
- Does a small subset of https://github.com/ScottLogic/datahelix/pull/1040.
- Does not report contradictions to the user, but fails silently, generating no data.
Resolves #1062 
Resolves #988 
Related #896
> 896 upfront contradictory pruning minimal - fails silently

- README.md
All Projects come into incubating status (so fixing the badge) and updates github absolute links to point to finos github org (albeit they worked also in the previous edition, given to seamless github redirect on transfer).
> Updated "incubating" badge / cosmetic links update

- generator/src/main/java/com/scottlogic/deg/generator/decisiontree/NodeMarking.java
- generator/src/main/java/com/scottlogic/deg/generator/decisiontree/visualisation/DecisionTreeVisualisationWriter.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/DataGeneratorMonitor.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/DecisionTreeDataGenerator.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/MessagePrintingDataGeneratorMonitor.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/NoopDataGeneratorMonitor.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/ReductiveDataGeneratorMonitor.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/UpfrontTreePruner.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/VelocityMonitor.java
- generator/src/main/java/com/scottlogic/deg/generator/guice/GeneratorModule.java
- generator/src/main/java/com/scottlogic/deg/generator/guice/MonitorProvider.java
- generator/src/main/java/com/scottlogic/deg/generator/validators/ContradictionDecisionTreeValidator.java
- generator/src/main/java/com/scottlogic/deg/generator/validators/StaticContradictionDecisionTreeValidator.java
- generator/src/test/java/com/scottlogic/deg/generator/builders/AtomicConstraintBuilder.java
- generator/src/test/java/com/scottlogic/deg/generator/builders/ConstraintNodeBuilder.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/DecisionTreeDataGeneratorTests.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/UpfrontTreePrunerTests.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/VelocityMonitorTests.java
- orchestrator/src/main/java/com/scottlogic/deg/orchestrator/visualise/VisualiseExecute.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/utils/CucumberTestModule.java
Full contradictions reported to the user like this:
Partial contradictions reported to the user like this:
- UpfrontTreePruner updated to use the contradiction checking used in the visualiser to report contradictions.
- Helper function added to monitors to allow easier printing after generation.
- Added unit and integration tests.
- Removed the reference to static contradictions, because all contradictions should be picked up.
Meets basic requirements of #896
Meets basic requirements of #383
> User gets error message if their profile has a partial or full contradiction.

- output/src/main/java/com/scottlogic/deg/output/writer/json/JsonDataSetWriter.java
```
[ {
"field" : "1"
} ]
```
```
[ {
"field" : 1
} ]
```
Resolves #1000
> Fix - Integers are now outputted to JSON as numbers and not strings.

- examples/from-file/profile.json
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/validator/ProfileValidationTests.java
- profile/src/main/resources/profileschema/0.1/datahelix.schema.json
- profile/src/test/resources/test-profiles/valid/simple-anyof-allof.json
- profile/src/test/resources/test-profiles/valid/simple-data-constraints-nested-2level.json
- profile/src/test/resources/test-profiles/valid/simple-data-constraints-nested-7level.json
- profile/src/test/resources/test-profiles/valid/simple-data-constraints.json
- profile/src/test/resources/test-profiles/valid/simple-not.json
This PR adds a test which checks the example profiles against the schema. This could help us to ensure we keep the schema updated and do not break backwards compatability. At present the schema is not always updated to keep up with new syntax. 
Unlike the old tests this does not run the generator - just the schema validator. This should ensure these tests remain fast and focused. 
- New DynamicTest collection of tests added which tests all example profiles.
- Schema updated - `aVaild` removed as acceptable syntax, name/financial code types added, `setFromFile` added
- Small edit to `from-file` example as it had an allOf containing only one constraint which the schema does not see as valid
Resolves #1031
> Example profile validation tests

- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/validator/ProfileValidationTests.java
When I created a new file in [this PR](https://github.com/finos/datahelix/pull/1123) I forgot to add the licence header. This PR inserts it.
> Add missing license header

- docs/GettingStarted/CreatingAProfile.md
- docs/Options/GenerateOptions.md
- docs/Options/ViolateOptions.md
- generator/docs/ProfileValidation.md
- orchestrator/src/main/java/com/scottlogic/deg/orchestrator/generate/GenerateCommandLine.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/utils/CucumberGenerationConfigSource.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/endtoend/loadfiletest.profile.json
- profile/src/main/java/com/scottlogic/deg/profile/guice/ProfileConfigSource.java
- profile/src/main/java/com/scottlogic/deg/profile/guice/ProfileSchemaValidatorProvider.java
This PR reverts schema validation to be on by default - this was turned off in [this PR](https://github.com/finos/datahelix/pull/829) due to lack of confidence in the schema. However, with the schema now once again being tested against example profiles (and hopefully people adding to this/updating schema when making changes) it seems like a good idea to make this the default again.
- Makes schema validation once again on by default
- Changes `--enable-schema-validation` back to `--disable-schema-validation`
- Updates documentation to make this clear
- Removes references to CLI option `--validate-profile` as this doesn't exist as a valid option
Still disabled when running generator through cucumber.
> Reenable schema validation

- generator/src/main/java/com/scottlogic/deg/generator/generation/DecisionTreeDataGenerator.java
- generator/src/main/java/com/scottlogic/deg/generator/guice/GeneratorModule.java
- generator/src/main/java/com/scottlogic/deg/generator/walker/RandomReductiveDecisionTreeWalker.java
- generator/src/main/java/com/scottlogic/deg/generator/walker/ReductiveDecisionTreeWalker.java
- generator/src/main/java/com/scottlogic/deg/generator/walker/ReductiveWalkerRetryChecker.java
- generator/src/main/java/com/scottlogic/deg/generator/walker/RetryLimitReachedException.java
- generator/src/test/java/com/scottlogic/deg/generator/walker/RandomReductiveDecisionTreeWalkerTests.java
- generator/src/test/java/com/scottlogic/deg/generator/walker/ReductiveDecisionTreeWalkerTests.java
- generator/src/test/java/com/scottlogic/deg/generator/walker/ReductiveWalkerRetryCheckerTests.java
- orchestrator/src/main/java/com/scottlogic/deg/orchestrator/generate/GenerateExecute.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/generate/GenerateExecuteTests.java
- Added retry limit to the Reductive Walker so it can't get into an infinite loop.
- This could cause some profiles with partial contradictions to be unable to produce data when they should be able to. There are other alternatives to this approach, e.g. by resolving #1090 or by making a new walker that supersedes the Reductive Walker.
- Currently does not inform user of error, just ends silently. Gives a warning message could be done in a separate PR.
Resolves #1087 
Resolves #1092 
Resolves #1139 
Makes #1090 less important.
> 1087, 1092 add retry limit to reductive walker

- profile/src/main/resources/profileschema/0.1/datahelix.schema.json
The 'value' part of a constraint must be a plain string, datetime or number. This gives a better warning message when schema validation is enabled (which it is by default) and the user makes the easy mistake of typing 'value' instead of 'values' for an inSet constraint.
Profile (Lines 12-16):
```
{
"field": "X",
"is": "inSet",
"value": [1, 2, 3]
}
```
Old:
```
* Error(s) occurred during schema validation.
File path: docs\GettingStarted\ExampleProfile1.json
For full details try opening the profile in a json schema-enabled IDE.
See https://github.com/finos/datahelix/blob/master/docs/ProfileDeveloperGuide.md#Microsoft-Visual-Studio-Code
* Problem found at line 14
... "is": "inSet", ...
Suggested fix:
- The value must be one of ["ofType", "equalTo", "formattedAs", "matchingRegex", …
```
> 1049 - Update Profile Schema

- .github/CONTRIBUTING.md
Add documentation on how to auto-generate copyright header in new java files within intellij
.giithub/CONTRIBUTING.md is only file changed
> feat(#1162): Add documentation on copyright header in intellij

- common/build.gradle
- common/src/main/java/com/scottlogic/deg/common/util/NumberUtils.java
- common/src/test/java/com/scottlogic/deg/common/util/NumberUtilsTests.java
- generator/build.gradle
- generator/src/main/java/com/scottlogic/deg/generator/generation/string/RegexStringGenerator.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/string/RegexStringGeneratorTests.java
- generator/src/test/java/com/scottlogic/deg/generator/helpers/StringGeneratorHelper.java
- generator/src/test/java/com/scottlogic/deg/generator/restrictions/TextualRestrictionsTests.java
Prevent RegexStringGenerator getting numerical overflow for matchedStringIdx and make sure tests still pass.  Not attempting to analyse or rewrite the class - can do that as separate bit of work if we think we need to.
Changes all within RegexStringGenerator
I added some tests to RegexStringGeneratorTest of which some failed until i did this change
I also fixed up an erroneous test in TextualRestrictionsTest so its a valid test
I added a StringGeneratorHelper.  Its only used in one test but can be used in more - which will do in ticket #1075 
This is not an attempt to understand and improve a class I don't understand very well.  If we get more issues then we can do this in which case we should speak to Mark H to see if he cna shed some light on what the class is meant to do.
Related to …
> fix(#1154): Fix RegexStringGenerator numerical overflow bug

- profile/src/main/java/com/scottlogic/deg/profile/reader/JsonProfileReader.java
- profile/src/test/java/com/scottlogic/deg/profile/reader/JsonProfileReaderTests.java
have JsonProfileReader explicity take in the mainConstraintReader rather than access it indirectly
this makes it clearer where the entry point to the constraint reading is.
> improve JsonProfileReader

- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/endtoend/JarExecuteTests.java
Explain that they can fail if code incorrectly prints to System.out.
This previously caught me out in https://github.com/finos/datahelix/pull/1179
Resolves #1180
> fix(#1180): Updated Jar Execute tests

- README.md
- docs/developer/KeyDecisions.md
- docs/user/UserGuide.md
- examples/string/README.md
- examples/string/profile.json
- generator/src/main/java/com/scottlogic/deg/generator/generation/string/AutomatonUtils.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/string/AutomatonUtilsTests.java
- generator/src/test/java/com/scottlogic/deg/generator/restrictions/TextualRestrictionsTests.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/ExhaustiveCombination-SpecialChars.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/ExhaustiveCombination.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/general/EqualTo-SpecialChars.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/general/InSet-SpecialChars.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/general/InSet.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/string/CharacterSet.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/string/ContainingRegex-SpecialChars.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/string/ContainingRegex.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/string/MatchingRegex-SpecialChars.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/string/MatchingRegex.feature
Change string generation to pick from latin characters
The character set has been restriceted to the range between U+0020 and U+007E.
Documentation and tests have been updated.
Note that this does not satisfy all acceptance criteria in #1075 specifically there is not command line argument which can toggle the feature.
Related to #1075
Had merge issue withoriginal PR #1138 so cherry picked into this PR
> 1075 Change string generation to pick from latin characters

- docs/user/UserGuide.md
- examples/from-file-weighted/profile.json
- examples/from-file/profile.json
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/endtoend/loadfiletest.profile.json
- profile/src/main/java/com/scottlogic/deg/profile/reader/AtomicConstraintTypeReaderMap.java
- profile/src/main/java/com/scottlogic/deg/profile/reader/constraintreaders/SetReader.java
- profile/src/main/java/com/scottlogic/deg/profile/v0_1/AtomicConstraintType.java
- profile/src/main/java/com/scottlogic/deg/profile/v0_1/ConstraintDTO.java
- profile/src/main/resources/profileschema/0.1/datahelix.schema.json
call sets from file using 
{ "field": "country", "is": "inSet", "file": "countries.csv" }
instead of 
{ "field": "country", "is": "setFromFile", "value": "countries.csv" }
Resolves #1165
> feat(#1165): call set from file using "file" instead of "values"

- generator/src/main/java/com/scottlogic/deg/generator/generation/string/ChecksummedCodeStringGenerator.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/string/IsinStringGenerator.java
- generator/src/main/java/com/scottlogic/deg/generator/utils/ProjectingIterable.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/general/OfTypeFinancialCodes.feature
isin's aren't unique in full sequential
currently generates all possible isins, then modifies ones with bad checksums to have the correct checksum. this causes lots of duplication
now it filters out the bad isins, which is inneficient
future work should be to change how isins are generated
Resolves #1192
> feat(#1192): filter out malformed isins instead of changing them

- generator/src/main/java/com/scottlogic/deg/generator/generation/string/RegexStringGenerator.java
Fixes crash. Checked by creating a long running process that goes past the 22nd million row.
The issue was caused by a signed `int` overflow causing the index to be negative, and hence illegal.
A long has twice the number of significant digits, so we would expect long to fail in the same way if the generator is run for a factor of over `10^9` longer than for the crash that happened previously.
Resolves #1203
> fix(#1203): Fix crash on long running generation

- docs/developer/HowToAddSupportForNewSchemaVersion.md
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/endtoend/JarExecuteTests.java
- profile/src/main/java/com/scottlogic/deg/profile/serialisation/SchemaVersionGetter.java
- profile/src/main/java/com/scottlogic/deg/profile/v0_1/SupportedVersionChecker.java
- profile/src/main/java/com/scottlogic/deg/profile/v0_1/SupportedVersionsGetter.java
- profile/src/test/java/com/scottlogic/deg/profile/v0_1/SupportedVersionCheckerTests.java
- profile/src/test/java/com/scottlogic/deg/profile/v0_1/SupportedVersionsGetterTests.java
Searches profile/src/main/resources/profileschema/ for sub-directories. The names of these directories are counted as valid schema versions. Previously the valid schema versions were hard-coded.
This could be more fragile than hard-coding the value. The trade-off between this and the old way needs to be considered.
Related to #1146
> 1146 smart directory searching

- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/validator/ProfileValidationTests.java
- profile/src/main/resources/profileschema/0.2/datahelix.schema.json
- profile/src/test/java/com/scottlogic/deg/profile/v0_1/ProfileSchemaValidatorLeadPonyTests.java
- profile/src/test/java/com/scottlogic/deg/profile/v0_1/ProfileSchemaValidatorMedeiaTests.java
- profile/src/test/java/com/scottlogic/deg/profile/v0_1/ProfileSchemaValidatorTests.java
- profile/src/test/resources/test-profiles/invalid/date-after-dynamic-with-incorrect-relation.json
- profile/src/test/resources/test-profiles/invalid/invalid-schema-version.json
- profile/src/test/resources/test-profiles/invalid/v0-2-features-in-v0-1-profile.json
- profile/src/test/resources/test-profiles/valid/date-equal-to-dynamic-offset.json
- Restricted allow schemaVersion of 0.2 schema version to just 0.2.
- Removed unneeded schema version testing.
- Added test profiles for testing the schema versioning:
- One valid 0.2 profile.
- One profile with an invalid schemaVersion.
- One invalid 0.2 profile.
- One valid 0.2 profile labelled as 0.1.
> Improve integration testing of schema versioning

- generator/src/main/java/com/scottlogic/deg/generator/generation/string/AutomatonUtils.java
Determise the automaton after the character set is restricted.
This appears to improve performance for large  profiles
Related to #1190
> perf(#1190): Determise the automaton after the char set is restricted

- generator/src/main/java/com/scottlogic/deg/generator/generation/DecisionTreeDataGenerator.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/combinationstrategies/CombinationStrategy.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/combinationstrategies/ExhaustiveCombinationStrategy.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/combinationstrategies/MinimalCombinationStrategy.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/combinationstrategies/PinningCombinationStrategy.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/combinationstrategies/ReductiveCombinationStrategy.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/databags/RowSpecDataBagGenerator.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/combinationstrategies/CombinationStrategyTester.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/combinationstrategies/ExhaustiveCombinationStrategyTests.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/combinationstrategies/MinimalCombinationStrategyTests.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/combinationstrategies/PinningCombinationStrategyTests.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/combinationstrategies/ReductiveCombinationStrategyTests.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/databags/RowSpecDataBagGeneratorTests.java
Fixes stream creating a collection big enough to go out of memory.
Happy to discuss best testing strategy for this issue. To test I have manually run in the profile. The issue appears to be an internal detail of the method, so in order to test I'd have to expose internals, or verify that it doesn't throw an exception when run (?).
I think an integration test is the most appropriate way, but this should probably come under a larger umbrella discussion of the best way to go about testing.
Resolves #1230
> fix(#1230): Prevent exhaustive mode from hanging

- docs/user/CombinationStrategies.md
- docs/user/generationTypes/GenerationTypes.md
- orchestrator/src/main/java/com/scottlogic/deg/orchestrator/generate/GenerateCommandLine.java
- Change combination strategy flag to not be hidden.
- Update docs to reflect actual default behaviour.
- Added a few links to make it easier to find information on combination strategy.
Resolves #1234
> Reenable combination strategy as a command line argument

- output/src/main/java/com/scottlogic/deg/output/writer/json/JsonDataSetWriter.java
use 24 hour date format in JSON output rather than 12 hour
changed hh to HH in the JsonDataSetWriter
> use 24 hour date format in JSON output

- generator/src/main/java/com/scottlogic/deg/generator/restrictions/TextualRestrictions.java
- generator/src/test/java/com/scottlogic/deg/generator/restrictions/TextualRestrictionsTests.java
Removed optimisation check in the method `isContradictory` which would incorrectly return false if the lengths where contradictory but there was no regex patterns on the object. Updated the test file to be more standard.
Resolves #1220
> 1220 duplicate constraint error

- profile/src/main/java/com/scottlogic/deg/profile/reader/atomic/FromFileReader.java
Updated the FromFileReader constructor so if the provided file path doesn't have a trailing file separator it will append one.
Resolves #1196
> fix(#1196): fixed reading directory paths without trailing separator

- docs/UserGuide.md
- docs/user/Schema.md
- profile/src/main/java/com/scottlogic/deg/profile/dto/FieldDTO.java
- profile/src/main/java/com/scottlogic/deg/profile/reader/JsonProfileReader.java
- profile/src/main/resources/profileschema/0.5/datahelix.schema.json
- profile/src/test/java/com/scottlogic/deg/profile/ProfileSchemaImmutabilityTests.java
- profile/src/test/java/com/scottlogic/deg/profile/ProfileSerialiserTests.java
- profile/src/test/java/com/scottlogic/deg/profile/reader/JsonProfileReaderTests.java
Updated the profile schema so that the field definitions includes formatting and unique constraints. These have been removed from the constraints section of the profile. 
Backwards compatiblity for old schemas has been removed with this change but this will be addressed with issue #1315 
- New profile version with the new field definition block
- Updated user docs for the new schema
- Added unit tests for checking the parsing of the schema
Related to #1303
> 1303 expand field definitions formatting unique

- docs/UserGuide.md
- docs/user/Schema.md
- profile/src/main/java/com/scottlogic/deg/profile/dto/FieldDTO.java
- profile/src/main/java/com/scottlogic/deg/profile/reader/JsonProfileReader.java
- profile/src/main/resources/profileschema/0.6/datahelix.schema.json
- profile/src/test/java/com/scottlogic/deg/profile/ProfileSchemaImmutabilityTests.java
- profile/src/test/java/com/scottlogic/deg/profile/ProfileSerialiserTests.java
- profile/src/test/java/com/scottlogic/deg/profile/reader/JsonProfileReaderTests.java
Added nullable to the field definition in the profile schema. This is shorthand for creating the constraint not null for the field when nullable is false. By default nullable will be set to true.
- Added `nullable` to the profile schema for the field definition
- Updated user documentation
- Added unit tests
Resolves #1303
> 1303 expand field definitions nullable

- common/src/main/java/com/scottlogic/deg/common/profile/constraints/atomic/EqualToConstraint.java
Fixed up EqualToConstrint.toString so prints out string which includes field name and value
1 line change in EqualToConstraint
Resolves #1334
Related #1322
> 1334 EqualToConstraint toString bug

- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/general/EqualTo.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/grammatical/AllOf.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/string/ShorterThan.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/steps/GeneralTestStep.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/utils/CucumberTestHelper.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/utils/CucumberTestState.java
if not expecting exceptions in cucumber tests, don't catch the exceptions
Some tests duplicate, so deleted, one test ignored and issue raised, one test fixed
Resolves #1198
> chore(#1198): throw exceptions properly in cucumber tests

- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/general/FormattedAs.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/general/OfType.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/numeric/GranularTo-Decimal.feature
- profile/src/main/java/com/scottlogic/deg/profile/reader/MainConstraintReader.java
- profile/src/main/java/com/scottlogic/deg/profile/reader/atomic/AtomicConstraintValueReader.java
- profile/src/test/java/com/scottlogic/deg/profile/reader/ConstraintValidationAndReadingTests.java
Numeric values will be read as bigdecimal now rather than numeric
this also fixes the issue of passing in numbers to the profile surrounded in quotes.
this will now read correctly
> refactor(#1330): make numeric values bigdecimal throughout the system

- generator/src/main/java/com/scottlogic/deg/generator/fieldspecs/FieldSpecFactory.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/StandardFieldValueSourceEvaluator.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/fieldvaluesources/RealNumberFieldValueSource.java
- generator/src/main/java/com/scottlogic/deg/generator/restrictions/linear/NumericGranularity.java
- generator/src/main/java/com/scottlogic/deg/generator/restrictions/linear/NumericRestrictions.java
- generator/src/test/java/com/scottlogic/deg/generator/fieldspecs/FieldSpecTests.java
- generator/src/test/java/com/scottlogic/deg/generator/fieldspecs/NumericRestrictionsMergeOperationTests.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/StandardFieldValueSourceEvaluatorTests.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/fieldvaluesources/RealNumberFieldValueSourceTests.java
- generator/src/test/java/com/scottlogic/deg/generator/reducer/ConstraintReducerTest.java
- generator/src/test/java/com/scottlogic/deg/generator/restrictions/NumericRestrictionsMergerTests.java
- generator/src/test/java/com/scottlogic/deg/generator/restrictions/NumericRestrictionsTests.java
Cleaned up a bit of code and changed how blacklised values were being checked.
- Removed global limits from numericRestrictions class and changed all usuages of said limits to use the defaults class.
- Changed how blacklisted value filtering works 
Resolves #1359
Related to #1235
> 1359 Refactor blacklist filtering in RealNumberFieldValueSource

- profile/src/main/java/com/scottlogic/deg/profile/dto/ProfileSchemaValidatorLeadPony.java
Fix link in Schema validation error messege.
Now correctly links to https://github.com/finos/datahelix/blob/master/docs/GettingStarted.md#Profile-Validation
> Update link in schema validation error message

- .circleci/config.yml
Run the tests during the release job. This ensures the time taken for every master build on CircleCI accounts for the test suite.
Next actions, once we have verified the test results are being stored, is to check if Cucumber tests are working.
Related to #1248
> Add test building to master branch job

- generator/src/main/java/com/scottlogic/deg/generator/fieldspecs/FieldSpec.java
- generator/src/test/java/com/scottlogic/deg/generator/fieldspecs/FieldSpecTests.java
Added a whitelist check to the permits function in fieldSpec as previously it would return true even if the value was not in the whitelist.
Related to #1417
> fix(#1417): added whitelist check to permits fucntion in fieldSpec

- generator/src/main/java/com/scottlogic/deg/generator/decisiontree/ConstraintNode.java
- generator/src/main/java/com/scottlogic/deg/generator/decisiontree/ConstraintNodeBuilder.java
- generator/src/main/java/com/scottlogic/deg/generator/decisiontree/DecisionNode.java
- generator/src/main/java/com/scottlogic/deg/generator/decisiontree/DecisionTreeFactory.java
- generator/src/main/java/com/scottlogic/deg/generator/decisiontree/DecisionTreeOptimiser.java
- generator/src/main/java/com/scottlogic/deg/generator/decisiontree/DecisionTreeSimplifier.java
- generator/src/main/java/com/scottlogic/deg/generator/reducer/ConstraintReducer.java
- generator/src/main/java/com/scottlogic/deg/generator/validators/ContradictionDecisionTreeValidator.java
- generator/src/main/java/com/scottlogic/deg/generator/walker/decisionbased/RowSpecTreeSolver.java
- generator/src/main/java/com/scottlogic/deg/generator/walker/pruner/PrunedConstraintState.java
- generator/src/main/java/com/scottlogic/deg/generator/walker/pruner/TreePruner.java
- generator/src/test/java/com/scottlogic/deg/generator/builders/TestConstraintNodeBuilder.java
- generator/src/test/java/com/scottlogic/deg/generator/decisiontree/ConstraintNodeTest.java
- generator/src/test/java/com/scottlogic/deg/generator/decisiontree/DecisionTreeFactoryTests.java
- generator/src/test/java/com/scottlogic/deg/generator/decisiontree/DecisionTreeSimplifierTests.java
- generator/src/test/java/com/scottlogic/deg/generator/decisiontree/treepartitioning/ConstraintToFieldMapperTests.java
- generator/src/test/java/com/scottlogic/deg/generator/decisiontree/treepartitioning/TreePartitionerTests.java
- generator/src/test/java/com/scottlogic/deg/generator/reducer/ConstraintReducerTest.java
- generator/src/test/java/com/scottlogic/deg/generator/walker/decisionbased/RowSpecTreeSolverTests.java
Convert collections to sets around constraint node.
Fix logic in row spec decision solver around partial contradictions.
Performance is equivalent for a sample profile for 100,000 rows.
Duplicate constraints are still handled correctly.
Node markings are now considered for equality between constraints.
Resolves #1324
> 1324 constraint node cleanup

- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/temporal/GranularTo-DateTime.feature
Added tests to test the change to relax the datetime validation
Tests added for supplying the date in the following formats:
Millis
Seconds
Minutes
Hours
Days
Months
Years
We may not need the months/years tests but I have included them for now
Related to #1426
> test(#1426): add tests for relaxing datetime validation

- generator/src/main/java/com/scottlogic/deg/generator/generation/grouped/FieldSpecGroupValueGenerator.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/numeric/FieldDependencies.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/numeric/GranularTo-Decimal.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/temporal/DateTimeOtherField-Multiple.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/steps/DateValueStep.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/steps/GeneralTestStep.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/steps/NumericValueStep.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/utils/CucumberTestState.java
Added cucumber tests for multiple related datetime fields.
Added new cucumber hooks for after field, before field, and equal to field.
Updated the function `findFirst` as if a field was related to more other fields but it was set via the `main` property then it wouldn't be run first. 
#1439 has been raised to deal with the failing scenario
Related to #1425
> test(#1425): added cucumber tests for multiple related date fields

- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/general/InMap.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/grammatical/AllOf.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/grammatical/AnyOf.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/grammatical/If.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/numeric/GranularTo-Decimal.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/numeric/LessThan.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/numeric/LessThanOrEqualTo.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/string/ContainingRegex.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/string/LongerThan.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/string/MatchingRegex.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/string/OfLength.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/string/ShorterThan.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/temporal/Before.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/validation/CorrectConstraintTypes.feature
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/steps/BooleanValueStep.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/steps/DateValueStep.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/steps/NullValueStep.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/steps/NumericValueStep.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/steps/RegexValueStep.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/steps/SetValueStep.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/steps/StringValueStep.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/testframework/utils/CucumberTestState.java
Updated cucumber hooks to be less permissive so a developer can go to the step when viewing a feature file. 
There is a new hook for each constraint that is typed so the type is correct when making the constraint. Due to this I've had to removed the tests that where testing for incorrect types on constraints, these should be recreated as unit tests.
> chore(#0): added cucumber hooks for all constraints with typing

- generator/src/test/java/com/scottlogic/deg/generator/generation/visualiser/VisualiserWriterFactoryTest.java
When running the tests, VisualiserWriterFactory was creating a file called `destination.dot` and not clearing up.  This PR uses a tempory directory to make sure the file is cleaned up.
Use a temporary directory in the VisualiserWriterFactortyTests.
Related to #1322
> chore(#0) stop visualiser writing to files when running tests

- profile/src/main/java/com/scottlogic/deg/profile/ConstraintDeserializer.java
- profile/src/main/java/com/scottlogic/deg/profile/reader/AtomicConstraintReader.java
- profile/src/main/java/com/scottlogic/deg/profile/reader/ConstraintReader.java
- profile/src/main/java/com/scottlogic/deg/profile/reader/JsonProfileReader.java
- profile/src/main/java/com/scottlogic/deg/profile/serialisation/ProfileSerialiser.java
- profile/src/main/java/com/scottlogic/deg/profile/serialisation/Serialiser.java
- profile/src/test/java/com/scottlogic/deg/profile/reader/JsonProfileReaderTests.java
Tidy up after #1460 
Top three on the ticket were not done here. First and third are being addressed in different tickets (#1482, #1484), other I couldn't think of a cleaner solution due to the method signatures overlapping somewhat (`int` argument vs. `Object` argument, which would be ambiguous for `Integer`). The only solution in my opinion would be to extract it out as a static method to another class, but if that's the case I might as well leave it as is to avoid coupling in separate places.
Resolves #1472
> 1472 tidy up constraint types

- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/endtoend/JarExecuteTests.java
- output/src/main/java/com/scottlogic/deg/output/writer/csv/CsvDataSetWriter.java
- output/src/test/java/com/scottlogic/deg/output/writer/csv/CsvDataSetWriterTest.java
Before this change null characters were used as "escape characters" to escape commas in csvs.
This is not desired behaviour.
Use the "minimal" quote mode with CSV reader. (see https://commons.apache.org/proper/commons-csv/apidocs/org/apache/commons/csv/QuoteMode.html)
Note that this will change the behaviour of outputted csvs. It will now be more inline with the RFC4180 format (ie now strings will only have quotes around them if they contain quotes, linebreaks or commas).
Resolves #1377 
Currently the formatter is tied to databag. It could be seperated out into a seperate class.
> 1377 csv commas fix

- common/src/main/java/com/scottlogic/deg/common/profile/DateTimeGranularity.java
- common/src/main/java/com/scottlogic/deg/common/profile/Granularity.java
- common/src/main/java/com/scottlogic/deg/common/profile/NumericGranularity.java
- common/src/main/java/com/scottlogic/deg/common/util/GranularityUtils.java
- generator/src/main/java/com/scottlogic/deg/generator/fieldspecs/relations/AfterOffsetRelation.java
- generator/src/main/java/com/scottlogic/deg/generator/fieldspecs/relations/BeforeOffsetRelation.java
- generator/src/test/java/com/scottlogic/deg/generator/fieldspecs/relations/AfterDateRelationTest.java
- generator/src/test/java/com/scottlogic/deg/generator/fieldspecs/relations/BeforeDateRelationTest.java
- generator/src/test/java/com/scottlogic/deg/generator/fieldspecs/relations/FieldSpecRelationTest.java
- orchestrator/src/test/java/com/scottlogic/deg/orchestrator/cucumber/features/operators/temporal/DateTimeOtherField.feature
- profile/src/main/java/com/scottlogic/deg/profile/factories/relation_factories/FieldSpecRelationFactory.java
Allow beforeOffset and afterOffset relations.
E.g. foo is 3 days before bar, where bar is also a variable with its own constraints.
Change the behaviour of granulairity and constraints to allow finding previous values as well as next values.
Add the beforeOffsetRelation
Resolves #1453
> 1453 allow offset to be applied to before and after

- generator/src/main/java/com/scottlogic/deg/generator/fieldspecs/FieldSpecFactory.java
- generator/src/main/java/com/scottlogic/deg/generator/fieldspecs/GeneratorFieldSpec.java
A small tidy of FieldSpecFactory. Changed a Function<T, Boolean> to a
predicate, referred to string defaults instead of hardcoding and disallowed the implicit public constructor.
Related to #1404
> refactor(#1448): Tidy FieldSpecFactory

- common/src/main/java/com/scottlogic/deg/common/util/Defaults.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/string/factorys/RandomStringFactory.java
- generator/src/main/java/com/scottlogic/deg/generator/generation/string/generators/RegexStringGenerator.java
- generator/src/main/java/com/scottlogic/deg/generator/profile/constraints/atomic/AfterConstantTimeConstraint.java
- generator/src/main/java/com/scottlogic/deg/generator/profile/constraints/atomic/AfterConstraint.java
- generator/src/main/java/com/scottlogic/deg/generator/profile/constraints/atomic/AfterOrAtConstraint.java
- generator/src/main/java/com/scottlogic/deg/generator/profile/constraints/atomic/AfterOrEqualToConstantTimeConstraint.java
- generator/src/main/java/com/scottlogic/deg/generator/profile/constraints/atomic/BeforeConstantTimeConstraint.java
- generator/src/main/java/com/scottlogic/deg/generator/profile/constraints/atomic/BeforeConstraint.java
- generator/src/main/java/com/scottlogic/deg/generator/profile/constraints/atomic/BeforeOrAtConstraint.java
- generator/src/main/java/com/scottlogic/deg/generator/profile/constraints/atomic/BeforeOrEqualToConstantTimeConstraint.java
- generator/src/main/java/com/scottlogic/deg/generator/profile/constraints/atomic/GranularToDateConstraint.java
- generator/src/main/java/com/scottlogic/deg/generator/profile/constraints/atomic/GranularToTimeConstraint.java
- generator/src/main/java/com/scottlogic/deg/generator/profile/constraints/atomic/GreaterThanConstraint.java
- generator/src/main/java/com/scottlogic/deg/generator/profile/constraints/atomic/GreaterThanOrEqualToConstraint.java
- generator/src/main/java/com/scottlogic/deg/generator/profile/constraints/atomic/LessThanConstraint.java
- generator/src/main/java/com/scottlogic/deg/generator/profile/constraints/atomic/LessThanOrEqualToConstraint.java
- generator/src/main/java/com/scottlogic/deg/generator/restrictions/linear/LinearRestrictionsFactory.java
- generator/src/main/java/com/scottlogic/deg/generator/utils/GeneratorDefaults.java
- generator/src/test/java/com/scottlogic/deg/generator/fieldspecs/FieldSpecTests.java
- generator/src/test/java/com/scottlogic/deg/generator/fieldspecs/RestrictionsMergeOperationTest.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/FieldSpecGetFieldValueSourceTests.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/fieldvaluesources/RealNumberFieldValueSourceTests.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/fieldvaluesources/datetime/DateTimeFieldValueSourceTests.java
- generator/src/test/java/com/scottlogic/deg/generator/generation/string/RegexStringGeneratorTests.java
- generator/src/test/java/com/scottlogic/deg/generator/restrictions/DateTimeRestrictionsMergerTests.java
- generator/src/test/java/com/scottlogic/deg/generator/restrictions/DateTimeRestrictionsTests.java
- generator/src/test/java/com/scottlogic/deg/generator/restrictions/NumericRestrictionsMergerTests.java
- generator/src/test/java/com/scottlogic/deg/generator/restrictions/NumericRestrictionsTests.java
Previously string lengths would follow a geometric distribution between
the min and max, where each successive term would have a 3/10 chance of
being the terminal character added to the string.
Therefore in the previous case, regardless of the maximum (where the maximum is at
least 5 greater than the minimum), typically 50% of the values would be
within 2 characters of the minimum length.
This change instead generates up to the maximum length (our current
default is 1,000), and slices randomly between the min and max length.
This change appears to cut performance by about half for the example
given in shorter-than, at the advantage of giving a uniform
distribution. Note that this is for a single string (so the cost is likely to be greater for more strings), but also for a very extreme …
> fix(#1187): String lengths are uniformly random

- docs/UserGuide.md
User guide fix
Fix greaterThanField title in user guide.
- fix link
- fix markdown formatting
> docs(#1539): fix formmating error in user guide

- .eslintrc
- .gitignore
- package-lock.json
- package.json
- playground/index.html
- playground/index.js
Here's my proposed approach (and a rough and ready prototype) for a more lightweight online playground for DataHelix. You can see it in action here:
https://colineberhardt.github.io/datahelix/playground/
Note, you can share profiles via URL encoding, e.g. 
https://colineberhardt.github.io/datahelix/playground/#ewogICAgICAgICAgInNjaGVtYVZlcnNpb24iOiAiMC4xNyIsCiAgICAgICAgICAiZmllbGRzIjogW3sgIm5hbWUiOiAiZmlyc3ROYW1lIiwgInR5cGUiOiAic3RyaW5nIiB9XSwKICAgICAgICAgICJydWxlcyI6IFsKICAgICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAgICJydWxlIjogImZpcnN0IG5hbWUgY29uc3RyYWludHMiLAogICAgICAgICAgICAgICAgICAiY29uc3RyYWludHMiOiBbCiAgICAgICAgICAgICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAgICAgICAgICAgImZpZWxkIjogImZpcnN0TmFtZSIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgIm1hdGNoaW5nUmVnZXgiOiAiW2Etel17MSwxMH0iCiAgICAgICAgICAg …
> docs: added an interactive playground for datahelix

- core/src/main/java/com/scottlogic/datahelix/generator/core/fieldspecs/FieldSpecGroup.java
If two (or more) fields had different granularities, they would
intermittently fail depending upon the order the fields are resolved.
This therefore would cause non-deterministic failures. To fix this, an
error is explicitly thrown if the user attempts to create a relation
between two fields of different granularities.
Resolves #1566
> fix(#1566): Prevent different granularity on same field

- profile/src/main/resources/profileschema/datahelix.schema.json
Edits the Schema to remove dependency on schema version.
Edits the Schema to allow for any `faker.<--->.<--->` field to be allowed to be specified as a type.
Tested on a few profiles
```
{"fields": [ { "name": "jobTitle", "type": "faker.job.title", "nullable": true } ] }
```
```
{"fields": [ { "name": "a", "type": "faker.b.c", "nullable": true } ] }
```
But there are currently no automated tests in this area
Resolves #1569
> 1569 update schema for faker support

- core/src/main/java/com/scottlogic/datahelix/generator/core/fieldspecs/relations/EqualToOffsetRelation.java
- core/src/test/java/com/scottlogic/datahelix/generator/core/fieldspecs/relations/AfterRelationTest.java
- core/src/test/java/com/scottlogic/datahelix/generator/core/fieldspecs/relations/BeforeRelationTest.java
- core/src/test/java/com/scottlogic/datahelix/generator/core/fieldspecs/relations/EqualToRelationTest.java
- core/src/test/java/com/scottlogic/datahelix/generator/core/fieldspecs/relations/FieldSpecRelationTest.java
- examples/integerOffsetFromSet/README.md
- examples/integerOffsetFromSet/profile.json
Partial fix for the ticket #1489. This fixes the equal to case, but
doesn't address the before or after cases.
The reason for a partial fix is due to the difficulty comparing the two
different cases (equal vs before/after).
Equal to is simple because all of the values can be adjusted by the
offset, translating a set of values to a set of values.
Before/after are more complicated, as theoretically each of the values
must be translated to a range. This therefore means the result is a set
of restrictions. Unfortunately, the system isn't designed to be passing
around a set of restrictions at this time in the program. Therefore,
this will take further thought.
A possible solution is to take the most restrictive of the values. This
would ensure that whichever values are picked are permissable, …
> fix(#1489): Fix equal to offset for whitelist

- core/src/main/java/com/scottlogic/datahelix/generator/core/utils/JavaUtilRandomNumberGenerator.java
- core/src/test/java/com/scottlogic/datahelix/generator/core/generation/FieldSpecGetFieldValueSourceTests.java
- core/src/test/java/com/scottlogic/datahelix/generator/core/utils/JavaUtilRandomNumberGeneratorTest.java
Large integers (eg. across the maximum permitted range) were being
generated by converting a random `float` to a `BigDecimal`. This resulted in
a loss of precision, which often caused `int`s of approximately 15+
digits to have a sequence of zeros on the end.
This commit fixes the bug by utilising the structure of `BigDecimal` - a
`BigInteger` value with an `int` scale. By decomposing the structure and
operating using a random `BigInteger`, we can generated uniform values
across the specified range.
Resolves #1557
> fix(#1557): Fix distribution of large integers

- .whitesource
- whitesource.config
As part of FINOS infrastructure, we are enabling WhiteSource security scanning across all our hosted projects; this PR contains the bot configuration.
After this PR gets merged, I will personally enable the WhiteSource GitHub app and the scanning will begin: every build descriptor (ie pom.xml, package.json, etc) will be executed and all direct/transitive dependencies will be scanned for security vulnerabilities.
If any vulnerability is found, by default a new GitHub issue will be created, with all details needed by the team to investigate further; there may be false positives (ie vulnerabilities spotted on non-runtime dependencies), which must be tackled by updating the WhiteSource bot configuration.
Please note that the public scope of these issues may pose a security threat for …
> Enable WhiteSource integration for GitHub.com

- core/src/main/java/com/scottlogic/datahelix/generator/core/generation/string/generators/RegexStringGenerator.java
Previously any regex constraints, when combined with the faker type,
would run indefinitely. This occurs due to a bad assumption; that the
regex representation on the RegexStringGenerator are valid regexes. When
intersections occur, this is no longer the case. To avoid this, an error
is now thrown if an intersection or a union has occurred. This method is
only invoked from the Faker Generator.
Resolves #1584
> Error on regex faker

- playground/examples.json
- playground/index.html
- playground/index.js
- playground/style.css
Update Playground to use example profiles, and show more appropriate example by default.
- Introduce a list of curated example profiles (examples.json)
- Update playground to show the examples
- Remove initial profile content (replace with first loaded example)
Resolves #1596
> feat(#1596): Showcase examples in playground

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/ISSUE_TEMPLATE/Support_question.md
The issue templates are overly verbose at present and should be simplified.
- Change _question_ template to be more free-form
- Change _feature request_ template to be more free-form
- Change _bug report_ to be less structured
- Change each template to assign a label to each type of issue as they're created
Resolves #760
> chore(#760): Simplify issue template

- orchestrator/build.gradle
- profile/build.gradle
- profile/src/test/java/com/scottlogic/datahelix/generator/profile/validators/profile/ConstraintValidatorTests.java
- profile/src/test/java/com/scottlogic/datahelix/generator/profile/validators/profile/constraints/atomic/DateTimeGranularityValidatorTests.java
- profile/src/test/java/com/scottlogic/datahelix/generator/profile/validators/profile/constraints/atomic/EqualToConstraintValidatorTests.java
- profile/src/test/java/com/scottlogic/datahelix/generator/profile/validators/profile/constraints/atomic/GranularToConstraintValidatorTests.java
- profile/src/test/java/com/scottlogic/datahelix/generator/profile/validators/profile/constraints/atomic/LongerThanConstraintValidatorTests.java
- profile/src/test/java/com/scottlogic/datahelix/generator/profile/validators/profile/constraints/atomic/NumericConstraintValidatorTests.java
- profile/src/test/java/com/scottlogic/datahelix/generator/profile/validators/profile/constraints/atomic/OfLengthConstraintValidatorTests.java
- profile/src/test/java/com/scottlogic/datahelix/generator/profile/validators/profile/constraints/atomic/RegexConstraintValidatorTests.java
- profile/src/test/java/com/scottlogic/datahelix/generator/profile/validators/profile/constraints/atomic/ShorterThanConstraintValidatorTests.java
- profile/src/test/java/com/scottlogic/datahelix/generator/profile/validators/profile/constraints/atomic/TemporalConstraintValidatorTests.java
Previously atomic constraints were not individually unit tested. #1454 removed the cucumber tests that checked each constraints use with incorrect types or null values -- this PR recreates these tests at the unit level, in addition to testing other positive and negative cases.
Unit tests added for the following classes:
- DateTimeGranularityValidator
- EqualToConstraintValidator
- GranularToConstraintValidator
- LongerThanConstraintValidator
- NumericConstraintValidator
- OfLengthConstraintValidator
- RegexConstraintValidator
- ShorterThanConstraintValidator
- TemporalConstraintValidator
A couple of fixes also made to ConstraintValidatorTests
- Some tests are almost identically repeated across classes -- this is because the functionality is implemented in each class under test resulting …
> Add unit tests for atomic constraints

- playground/examples.json
- playground/index.html
- playground/index.js
Use more interesting demo in playground
- Default to demo/profile.json
- Display the README.md content in the `div` rather than in the content of the `table`.
- Use GitHub API to render markdown content into HTML
See [sl-slaing.github.io/datahelix/playground/](https://sl-slaing.github.io/datahelix/playground/)
Resolves #1595
> Use more interesting demo in playground

- .circleci/config.yml
- orchestrator/build.gradle
Embed release artefacts in a zip file, permitting the bundling of other files (e.g. scripts). Also supports the tool working with Chocolatey.
- New Gradle step to bundle the `.jar` file into `generator.zip`
- Updated CircleCI steps to invoke Gradle task
- Gradle release task updated to depend on `zip` rather than `fatJar`
Related to #1639
> #1639: Publish release artefacts as a zip file.

- .circleci/config.yml
- orchestrator/build.gradle
Use the gradle 'application' plugin to create the release zip file (rather than other means)
- Release zip now contains an 'expanded' jar file, no longer 1 (fat) jar file, but multiple
- Release zip contains bash and windows scripts to run the generator (orchestrator)
That is the zip file looks like:
- generator.zip
- generator
- bin
- datahelix (bash script)
- datahelix.bat (windows script)
- orchestrator (bash script)   - 👎 - not required
- orchestrator.bat (windows script)   - 👎 - not required
- lib
- many `jar` files, inc. orchestrator-[version]-.jar, common-[version].jar, etc.
Related to #1639
> chore(#1639): Use distZip (application) rather than hand-rolled zip method

- .gitignore
- Dockerfile
- docs/DeveloperGuide.md
- docs/GettingStarted.md
- docs/UserGuide.md
- orchestrator/build.gradle
- orchestrator/src/test/java/com/scottlogic/datahelix/generator/orchestrator/endtoend/JarExecuteTests.java
Rename release file to datahelix.zip (from generator.zip)
Related to #1639
> fix(#1639): Rename release artefact to datahelix.zip

- output/src/main/java/com/scottlogic/datahelix/generator/output/writer/json/JsonOutputWriterFactory.java
- output/src/test/java/com/scottlogic/datahelix/generator/output/writer/json/JsonOutputWriterFactoryTest.java
Fix JSON output to ensure it matches the NDJSON format when streaming
- Don't pretty-print JSON output when streaming
- JSON is still pretty-printed when not streaming (output to a file directly)
Resolves #1650
> #1650: Ensure JSON output matches NDJSON format

- orchestrator/src/test/java/com/scottlogic/datahelix/generator/orchestrator/cucumber/testframework/utils/CucumberFileReader.java
- orchestrator/src/test/java/com/scottlogic/datahelix/generator/orchestrator/validator/ProfileValidationTests.java
- profile/src/main/java/com/scottlogic/datahelix/generator/profile/reader/CsvFileInputReader.java
- profile/src/main/java/com/scottlogic/datahelix/generator/profile/reader/CsvInputReader.java
- profile/src/main/java/com/scottlogic/datahelix/generator/profile/reader/CsvInputStreamReaderFactory.java
- profile/src/main/java/com/scottlogic/datahelix/generator/profile/reader/CsvStreamInputReader.java
- profile/src/main/java/com/scottlogic/datahelix/generator/profile/reader/FileReader.java
- profile/src/main/java/com/scottlogic/datahelix/generator/profile/services/ConstraintService.java
- profile/src/main/java/com/scottlogic/datahelix/generator/profile/services/NameRetrievalService.java
- profile/src/test/java/com/scottlogic/datahelix/generator/profile/TestFileReader.java
- profile/src/test/java/com/scottlogic/datahelix/generator/profile/reader/JsonProfileReaderTests.java
- profile/src/test/java/com/scottlogic/datahelix/generator/profile/reader/file/CsvStreamInputReaderTest.java
- profile/src/test/java/com/scottlogic/datahelix/generator/profile/reader/file/names/NameRetrievalServiceTest.java
As identified in #1627, when a CSV file is read to provide the values for a set, it can fail if a row cannot be processed. This provides very little detail about the issue, and what corrective action could be performed.
- Refactoring to use less static method calls
- Throw an exception, with the following details if a value from a CSV cannot be used
- The line number and filename
- The value that couldn't be loaded (could not be parsed as a Double)
- Explanation of what corrective measures should be performed
e.g.
```
* Profile json is not valid
Weighting 'v.1' is not a valid number
CSV lines containing 2 values must hold a weighting (double) in the second column, e.g. <value>,0.5
Value: 'Sect.B', File: 'frequently_reprinted_subset-1.csv', Line 14
```
Also sufficiently resolves #1628 
``` …
```
> #1627: Provide additional detail if CSV read fails

- core/src/main/java/com/scottlogic/datahelix/generator/core/generation/DecisionTreeDataGenerator.java
- core/src/main/java/com/scottlogic/datahelix/generator/core/generation/LimitingDataGenerator.java
- core/src/main/java/com/scottlogic/datahelix/generator/core/generation/MonitoringDataGenerator.java
- core/src/main/java/com/scottlogic/datahelix/generator/core/guice/DataGeneratorProvider.java
- core/src/main/java/com/scottlogic/datahelix/generator/core/guice/GeneratorModule.java
- core/src/test/java/com/scottlogic/datahelix/generator/core/generation/DecisionTreeDataGeneratorTests.java
Refactor the architecture to use composition to control specific elements of how the generator behaves, rather than overloading a generator with too many responsibilities
- New generator to limit quantities of output
- New generator to monitor output
- Above functions removed from default (DecisionTreeDataGenerator)
Related to #1534
> refactor(#1534): Use composition to control generation behaviour

- orchestrator/src/main/java/com/scottlogic/datahelix/generator/orchestrator/generate/GenerateCommandLine.java
Fix issue with the generator when trying to use a profile in the same directory as the generator
- Convert a file as the command line argument to have an absolute path
Resolves #1677
> #1677- Ensure profileFile is expressed as an absolute path rather than relative

- playground/index.js
The old lambda has been removed. A new lambda behind an aws gateway located at https://un5ldd2avb.execute-api.eu-west-2.amazonaws.com/api/generator (POST) should be used going forward.
> Update lambda url

- playground/index.js
Fix the html table id for selecting with selenium - was rendering as `output"`, now `output`
Changed the playground output table id
Will be a seperate PR to add the selenium tests into master
Related to #1696
> chore(#1696): fix id on output table

- .travis.yml
Removes an unused file for Travis CI (we use circle CI on the datahelix).
> chore: Remove unused travis CI config

- gradle/wrapper/gradle-wrapper.properties
Local builds of the project with a fresh install of IntelliJ fail as the gradle wrapper version doesn't match that of the expected version of gradle (running as part of the build). As such the project cannot be built locally.
Update the gradle wrapper distribution version to v7 (latest)
Resolves #1726 
Relates to #1722
> Update gradle-wrapper distribution url to match configured version
